### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by joabakk** [SignalK/freeboard-sk#1]
Hi Rob,

I have been following your project and now I am moving to SK. I´m happy to see freeboard also moving to SK. But I can´t make sense of the installation procedure. If I already have a node server running, I should be able to install freeboard for SK directly?

**Comment by rob42** [comment]
The node server is not actually used, just the npm build/deploy functionality. The easiest way to get that on the platform is a std node.js install.

Basically it an experiment at the moment, when you install the signalk-server-java and start it you get an install page. By selecting freeboard-sk on that page the java server uses git to obtain the project, and 'npm build' to deploy it. Then it should be available. Upgrades are similar.

Its a bit broken at the moment, Im catching up on changes so your results may be a bit mixed.

Rob

January 26 2016 12:11 AM, "joabakk"  wrote:
	Hi Rob,

	I have been following your project and now I am moving to SK I´m happy to see freeboard also moving to SK But I can´t make sense of the installation procedure If I already have a node server running, I should be able to install freeboard for SK directly?

**Comment by rob42** [comment]
Closing as this is no longer valid
