### ISSUE TITLE
Freeboard doesn't quit loading screen after update: can't shift-reload on mobile device

### ISSUE THREAD

**Issue by martijn-heil** [SignalK/freeboard-sk#102]
After updating to the most recent version of freeboard, the loading screen hangs. The screen itself has the well-known message that you should shift-reload (in Firefox this is ctrl-reload), this works fine on devices with a proper keyboard, but on a smartphone running Firefox Mobile I can't figure out how to do a shift-reload style reload, if it's possible at all. I've solved it by going to Android Apps and clearing the cache for Firefox, but this is far from ideal.

**Comment by panaaj** [comment]
This is definietly a cache issue... 
My experience has shown me that even with the `no-cache` tags in `index.html `that some device / browser combinations still require the cache to be cleared.
Chrome on Android works OK (my main device)
I do not use Firefox on mobile device so it seems that the cache files are still being loaded by the browser.
Safari on iOS is OK but there have been reports when webviews are embedded in iOS apps (e.g. WilhelmSK) that the cached files are still used.
