### ISSUE TITLE
User defined units for pop-up window

### ISSUE THREAD

**Issue by KEGustafsson** [SignalK/freeboard-sk#104]
Would it be possible to add support for user defined units that are shown in pop-up window?
E.g.
- Lat,Lon: in addition to decimal system also DMS presentation
- Wind (T & A): m/s and maybe other common presentations 
- and the same for speed unit

**Comment by panaaj** [comment]
> * Lat,Lon: in addition to decimal system also DMS presentation

This is already possible by selecting the format in settings...
![image](https://user-images.githubusercontent.com/38519157/152281306-bbc07b15-d34a-461f-ba97-f5b7bdf1db5c.png)

I will look to add speed units selection with the following options:
- knots
- m/sec
- km/h
- mph

**Comment by KEGustafsson** [comment]
Excellent!

**Comment by tkurki** [comment]
One of these days we should define a shared model for the preferred units across applications.

![image](https://user-images.githubusercontent.com/1049678/152371826-7db66668-3be3-49cf-8df4-6ab920287eaa.png)
This is from InstrumentPanel, but both the user and global settings are just for IP.
