### ISSUE TITLE
Longitude issue with DMS position format

### ISSUE THREAD

**Issue by KEGustafsson** [SignalK/freeboard-sk#105]
It seems that Freeboard-SK is not calcullating/showing DMS correctly for longitude position on map for cursor or vessels.

Example of issue:
Goto 0° 0' 0'' longitude and move cursor either to east or west. Lon value is kept 0° 0' 0'' until it jumps to 1° 0' 0'' E/W and then minutes and seconds are updated. Same issue seems to be after every full degree change when moving to east.

When moving to west, there seems to be other kind of problem, there minutes goes up to 99 and same with seconds.

**Comment by panaaj** [comment]
I have created a fix. Will push a patch soon.
