### ISSUE TITLE
Automatically advancing to next waypoint

### ISSUE THREAD

**Issue by batuakan** [SignalK/freeboard-sk#106]
Would be possible to have setting that enables automatically advancing to the next way point when the boat enters in to the arrival circle?

It could also be beneficial if a route can be activated as forward or backwards

**Comment by panaaj** [comment]
These features are coming in a release that coincides with the server release which incorporates the course API.

**Comment by batuakan** [comment]
That is great news, is there an expected release date?

**Comment by panaaj** [comment]
Testing is currently being undertaken with a possible preview release in the near future.
This is a significant release and may require some plugins to be updated in line with the server release.

From a Freeboard point of view the features are basically ready (see screenshot).
- Automatic advancement on arrival alarm will be an option you can set (manual advancement is the default)
- Buttons on nav data bar at bottom of screen facilitate reversing the route, restarting course calculations, atrrival circle.
- Autopilot status is shown (where the data is present) and experimental support for PyPilot is also included.

![image](https://user-images.githubusercontent.com/38519157/154580881-95ef9ae8-da26-4a6e-b200-f4e03a05606f.png)

**Comment by panaaj** [comment]
Available in v2.0.0.

**Comment by panaaj** [comment]
V2.0.0 released.
