### ISSUE TITLE
Let the "select all" checkbox become "select filtered"

### ISSUE THREAD

**Issue by AndreasSchutz** [SignalK/freeboard-sk#107]
Hi Adrian
This is not a bug, but a feature request.

Why not let the "select all" checkbox in the panels for "Routes", "Waypoints", "Notes" and "Charts" become "select filtered" and let it handle what is visible in the filtered list. If you think this is a good idea, then with no filter (default) the checkbox handles all, and with a filter applied the checkbox handles what is filtered.

This is useful for creating pseudo groups of the content. I can (as an example) name all my west coast charts "West coast - Chartname1, West coast - Chartname2 ...and so on. If I then filter on "West coast" I will get all of those charts and I can activate them with the checkbox. Or I can select all the notes with the word "beach" in them and show the areas for my friends to select a destination! :-)

**Comment by panaaj** [comment]
v1.19.4 contains the update to filtering behaviour to address this.
