### ISSUE TITLE
AIS targets show MMSI instead of name

### ISSUE THREAD

**Issue by bergie-umi** [SignalK/freeboard-sk#108]
As of last couple of versions, Freeboard has only been displaying MMSI for AIS targets on the charts, not vessel names.

<img width="466" alt="Screenshot 2022-04-12 at 14 47 05" src="https://user-images.githubusercontent.com/64909253/162965870-7778a564-f63e-48c5-ad3a-fb8dc24fa46f.png">

You need to go to vessel properties to see it, which is cumbersome:

<img width="557" alt="Screenshot 2022-04-12 at 14 48 59" src="https://user-images.githubusercontent.com/64909253/162965964-20326d1c-42cc-4795-8915-291ada75ae32.png">

**Comment by panaaj** [comment]
I have checked with my setup (and also using the `n2k-from-file` source) and the names do display on the map and the popover displayed when the vessel is clicked.

To help identify where the issue may lie I will explain how data is collected for display....
1. The vessel name or  mmsi or callsignVhf (in that priority order) is used to label the vessel on the map. This information is sourced from the stream received over the websocket connection.
2. The details displayed in the Vessel Properties screen is sourced by an api call to the server at the time the `info` button is clicked.

So it seems that the `name` information is not being seen in the stream messages received by Freeboard.

Freeboard "builds" the information about a vessel from every message which contains the vessel's id as the context.
So the information held about a vessel will grow incrementally as messages are received.
Additionally freeboard will remove the record of a vessel if a message for that vessel is not received within the set period.
If this occurs and then messages are again received for that vessel, the information held will again grow incrementally as messages are received.

Are the names never displayed or are they initally displayed and then disappear?
