### ISSUE TITLE
Add support for skipping onboarding screen

### ISSUE THREAD

**Issue by bergie** [SignalK/freeboard-sk#110]
I'm running Freeboard embedded in a Grafana dashboard on a kiosk screen in our nav station

![20220419_123515](https://user-images.githubusercontent.com/3346/163989449-3018eaa7-3193-42a2-91d4-3db8a429f143.jpg)

Problem is that every time the screen starts we:

* Get shown the onboarding wizard (that doesn't quite fit the screen space)
* Lose "follow boat" setting
* Lose zoom level

Would be great to provide default values for those via URL parameters when opening the app. Then I could easily encode those to the iframe URL. For the moment I need to connect a mouse to the device to get to the desired view.

**Comment by panaaj** [comment]
It sounds like Freeboard cannot access localStorage where it stores its configuration so it starts with default values.
This happens in later versions of Chrome when Freeboard is placed within an IFrame and "Block third-party cookies" is selected in Chrome settings.
![image](https://user-images.githubusercontent.com/38519157/164122710-2d981d21-1318-419c-89bc-c5330086e979.png)

A short term fix is to change the setting and Freeboard will be able to access it's config.

I am looking to move Freeboard config out of localStorage in a future version.

**Comment by bergie** [comment]
This browser is running in kiosk mode, so inability to use localStorage is more of a feature than a bug in this case. That’s why I was wondering if it’d be possible to instead feed Freeboard default initialisation values via URL parameters.

**Comment by bergie** [comment]
Another useful option could be storing/fetching these settings server-side.  Would be nice to not have to run each client through the setup wizard again

**Comment by panaaj** [comment]
> Another useful option could be storing/fetching these settings server-side. Would be nice to not have to run each client through the setup wizard again

Freeboard already does this... Once you login (using the Login option in the Freeboard menu) it loads / saves config to the server.

**Comment by panaaj** [comment]
> This browser is running in kiosk mode, so inability to use localStorage is more of a feature than a bug in this case. That’s why I was wondering if it’d be possible to instead feed Freeboard default initialisation values via URL parameters.

Does Kiosk Mode limit access to LocalStorage? I thought it just launches an app in "Single App mode" so no other controls are available. It should not impact app operation.

**Comment by panaaj** [comment]
FYI: I have just tried chromium kiosk mode on my Rpi to launch Freeboard and it launches and retrieves persisted settings without an issue restoring selected settings, map position and zoom.

`chromium-browser --kiosk  http://localhost:3000/@signalk/freeboard-sk`

**Comment by bergie** [comment]
Yup, I just went through the source code of https://github.com/grafana/grafana-kiosk

It does indeed create a temp directory for Chromium user data, and nukes it afterwards. So not much chance in persistent storage here.

**Comment by bergie** [comment]
But ok, switching from grafana-kiosk to just starting Chromium on my own seems to do it. I think URL params would be nice, but for now considering this fixed. Thanks!

**Comment by panaaj** [comment]
@bergie url parameters for zoom, movemap, northup are included in v1.20.0.
Documented in help.

**Comment by bergie** [comment]
That's great, thanks! This means I can easily build contextual dashboards. For example, zooming very close when state is anchored so that the anchor watch circle is visible
