### ISSUE TITLE
Lock zoom to map - Functionality request

### ISSUE THREAD

**Issue by AndreasSchutz** [SignalK/freeboard-sk#115]
Easy to access toggle button to lock zoom level to what map can provide to prevent "over zooming" the map and getting a blank background.

Easy access is good because sometimes you want to continue zooming to levels where next map takes over.

The Lock button would be very good in situations that requires frequent zooming to get both overview and detail. Like in "power sailing" when racing and in dangerous situations in narrow waters and hard wind.

**Comment by panaaj** [comment]
Added to v2.1.0.
