### ISSUE TITLE
Make colour of AIS targets adjustable as it's not legible with satellite imagery

### ISSUE THREAD

**Issue by zyxit2** [SignalK/freeboard-sk#118]
When using satellite image overlays in the map it is nearly impossible to read names of AIS targets – dark grey is not legible with dark blue background of the sea.

Please make it possible to change colour of the AIS target names.

<img width="727" alt="Freeboard SK" src="https://github.com/SignalK/freeboard-sk/assets/66992535/6b37a262-3ea8-49e6-b888-52ed06ae07e1">

**Comment by panaaj** [comment]
I can add a UI control to toggle the text color of AIS targets (e.g. black / yellow).
That should hopefully address your issue in the short term.

**Comment by zyxit2** [comment]
That would be great!
