### ISSUE TITLE
Cannot set Anchor Watch

### ISSUE THREAD

**Issue by Ric121** [SignalK/freeboard-sk#121]
I 'm trying to set up an anchor.
I go menu->Anchor Watch
In the Anchor Watch window I set a radius and i click on the RAISE / DROP boton
THen a Connection login windows popup to connect to Signal-k server. I fill up with credentials and press OK
The loggin window closes without reporting any error, but nothing happens. No circle is drawn.

I have installed the signalk-anchoralarm-plugin and it is enable (I just pressed submmit in the setting window)

What do I do wrong?

**Comment by panaaj** [comment]
There is a known issue when setting anchor watch when the server has security enabled.

A fix is being prepared and should be available soon.

**Comment by panaaj** [comment]
Fix is in v2.2.6.

_**Note:** Requires the v1.13.0 of `signalk-anchoralarm-plugin`!_

**Comment by Ric121** [comment]
Wow that was fast thank you very much
