### ISSUE TITLE
Anchor Watch looping raising notifcations

### ISSUE THREAD

**Issue by Ric121** [SignalK/freeboard-sk#122]
I don't know if it's an  issue or a feature, and if it's on freeboard side or the pluggin side.

I use the Anchor Watch on freeboard-sk and renotfier pluggin to send me a message on my phone every time a notification is raised.

When the anchor watch raised the notification, I receive a flow of continuous messages. It does not happen with other notifications I use (For instance temperature sensors through simple notification pluggin). 
It makes me feel that the Anchor Watch notification is raised again and again at every check, no regard of the previous status.
I'm not sure of the philosophy of notifications in Signal-k, but I don't see the point of keeping raising the same notification. Besides you loose the original timestamp information which can be important ("When did the problem started?" information).

**Comment by sbender9** [comment]
Very good point. This is definitely on the plugin side. I have always been a bit torn on this one. It's a pretty important notification.  One that could, in theory, be life threatening. I'm inclined to keep yelling at you to fix the issue. But also know how annoying it can be when I am leaving anchor, I forgot to turn off the anchor alarm, and shit is going on and that damn alarm keeps yelling at me!

**Comment by Ric121** [comment]
In my opinion, a notification should be raised once then lowered once, whatever it is, an alert or an emergency. The criticality of the notification should be handled through the "state" value by the client as needed, but not by the pluggin through repeating the notification. That's why there are different gradings from alarm to emergency.

And about Yelling, freeboard does it very well with only one notification raise up ;-)

If the client thinks it's life threatening and should repeat the notification, it could implements a "snooze" feature or something like that

If you have systems that catch the notification raise and do some treatment (as renotifier) it will collapse the computer. I received something like 300 Telegram messages this afternoon ;-)
