### ISSUE TITLE
unable to open playback connection

### ISSUE THREAD

**Issue by bgrr74** [SignalK/freeboard-sk#124]
Hi,

When i want to use the playback route option i get a warning "unable to open playback connection".

Installed signalk recently on a ubuntu 22.04 server.

installed influxdb2  on server
installed influxdb2 plugin in signalk

I can see data (nmea0183) being written in de influx DB from my nmea0183 Garmin Nexus server which is serial connected to my ubuntu server.

When i have the freeboard webapp open i can see the live route being plotted on the map and for example COG and DEPTH in the instrument panel.

When i close the freeboard webapp and continu sailing  that part of the track is not plotted in the freeboard map.
In the settings the option ""get trail from server" is enabled but only the track is plotted when freeboard map is open in browser.

Does the function " get trail from server" and playback  not work with influxdb2 ?
How can i check if i made a mistake in signal regarding influxdb2 ?

**Comment by tkurki** [comment]
Influxdb2 plugin does not yet support track api nor playblack.

https://github.com/tkurki/signalk-to-influxdb2/issues/30

https://github.com/tkurki/signalk-to-influxdb2/issues/31
