### ISSUE TITLE
Pypilot

### ISSUE THREAD

**Issue by voilier-kalymnos** [SignalK/freeboard-sk#127]
Hi, 
I connect my tinypilot (raspberry pi Zero W) via the local network to port 80 (via the plugin config of the signalkK server) and I get connection between freeboard web page and the pilot .
But  
1/ I can change the target with +1 -1 +10 -10
2/ the target should bee the BRG but it's not the case
3/ The mode nav didn't stay, going back to GPS all the times

Connecting the pypilot to the Chart Plotter is a great project.
Thank you for your work.

**Comment by panaaj** [comment]
I'm not familiar with Tinypilot operation but can describe the current functionality to hopefully assist in finding a solution.

Freeboard-SK communicates with pypilot via the websocket connection provided by `pypilot_web`.

So information displayed in Freeboard-SK is what is received from pypilot via this channel.
Same goes for the commands sent.

So the commands for +/-10 are flowing through.

The target value displayed is the `heading_command` value from pypilot.

The mode switching back reflects the value received from pypilot... Freeboard-SK only displays the information coming from the pilot so this would indicate the mod change was not successful.

Effectively Freeboard-SK is just acting as a terminal for the values received from pypilot_web.

Can Tinypilot be controlled by the pypilot web interface?

**Comment by panaaj** [comment]
Thanks for providing more details.

> 4. +1, -1, -10, +10 do nothing

I have prepared a fix for this which I will release soon.

> 5. When I set a route to active the target of the pypilot didn't take the BRG of the route

So with regards activating a route....Freeboard-SK sets this on the Signal K server (using the Course API) which populates the relevant paths on the Signal K server.
You will likely need to enable all the options in the `signalk-to-nmea0183` plugin to ensure APB, RMB, MWV sentences are generated for pypilot to see.

**Comment by voilier-kalymnos** [comment]
Thank you Andrian
With 2.3.1 the +1, -1, -10, +10 are working, congratulations!
I understand that the transfer of target value is between signalk server
and pypilot.
At this time it's not working and I am trying different configurations.
Sean d'epagnier (developer of pypilot) has confirmed to me that the
information should go via NMEA183 APB sentence...
Best regards
Vincent
