### ISSUE TITLE
Unable to Upload waypoints GPX

### ISSUE THREAD

**Issue by DrStS** [SignalK/freeboard-sk#128]
The Load GPX bottom is not allowing for upload of data. The bottom load is "grey". I am running the most recent version also for singalk ( 2.4.1). The resource provider plugin is default for singalk 2. 

I could not find anything in the documentation. Is there anything one needs to configure to get that enabled?

Thanks a lot!

Best Stefan

**Comment by panaaj** [comment]
Do you get the same result with all files or just this one?

Can you please provide a screenshot of the browser console (Ctrl-shift-i) and any errors it contains.

**Comment by panaaj** [comment]
Fix will be part of next release.
