### ISSUE TITLE
FeatureRequest: Add lay lines and integration with polar

### ISSUE THREAD

**Issue by joabakk** [SignalK/freeboard-sk#13]
https://github.com/SignalK/maptracker/issues/15
Lay lines could come from performance.beatAngle and/or performance.gybeAngle. Any route suggestions would need a way to get the full polar table/diagram, not currently represented in the schema. Repeating the linked issue for clarity: Another great feature would be to be able to suggest routes based on vessel polar diagram. See http://zezo.org/sodebo/chart.pl? for example. this requires polars (obviously), grib files and a definition of coastlines, eg. from OpenStreetMap.

**Comment by rob42** [comment]
Some time ago I came across an algorithm that defined a polar from misc vessel data obtained while sailing around in circles over time. See https://groups.google.com/forum/#!topic/signalk/YpmDpfv-Ro4

I got as far as adding code to record data, and was able to create a polar from it. But I never had enough time to finish it.
