### ISSUE TITLE
Charts coverage overview.

### ISSUE THREAD

**Issue by AndreasSchutz** [SignalK/freeboard-sk#130]
Yet another feature request. :-)

It would be very nice to be able to visualize coverage of the charts you have stored. When you buy charts the vendors sometimes show the outline of the chart you are going to buy with a colored line. (like this; https://www.bluev.co.uk/file-manager/Products/Navionics/Navionics%20Regular%20Charts/Navionics-UK-Regular_1000x1000.png).

Is that possible to implement?

**Comment by tkurki** [comment]
Some chart formats include metadata about `bounds`, like mbtiles https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#content

This feature really belongs in the chart plugin repo, as the feature would need support there. And this feature could be also an integral part of the plugin as well as chart using webapps like Freeboard.

**Comment by panaaj** [comment]
From a Freeboard-SK perspective, it would be quite straight forward to toggle on/off a chart boundary rectangle based on the chart bounds data _[bottom-left x, bottom-left y, top-right x, top-right y]_.

Example:
![image](https://github.com/SignalK/freeboard-sk/assets/38519157/6c0162f3-6d77-4f96-840b-ac1030424a4c)

**Comment by AndreasSchutz** [comment]
What you show on the picture is exactly what I had in mind. That would help a lot when you want to see water coverage of your installed charts. Often charts "step into action" at a Z value far to deep-zoomed to get an overview. Important is that you can show the boundary at a smaller Z value than the actual chart data is showing at, or a lot of the benefits will disappear. I.E. A chart with zoom level between Z12-Z16 must be able to show the boundary from Z6 (approx.) to give a real good overview. The best option (I believe) is to let the boundaries be visible in all zoom layers (???).

If this isn't a pain to implement, I think it will be very usable.

**Comment by AndreasSchutz** [comment]
@tkurki Do you think that the "boundary feature" will crash or behave crazy when the chart doesn't have the info. in the metadata? Today I only use mbtiles so I don't know how other charts behave.

**Comment by panaaj** [comment]
> The best option (I believe) is to let the boundaries be visible in all zoom levels (???).

The boundaries are visible at all zoom levels regardless of the chart metadata.

**Comment by tkurki** [comment]
Btw the assumption that the coverage is rectangular is too simple, see for example https://o-charts.org/shop/en/oesenc/75-italy-east-and-south-coast-including-sicily.html. Too bad mbtiles spec only talks about _(left, bottom, right, top)_.

Does anybody know about this with other map formats? Can somebody look into this?

The boundary feature naturally would need to work sensibly also in the absence of coverage data.

**Comment by tkurki** [comment]
Should we transfer this issue to the charts plugin? It would be nice to include a minimal webapp in the charts plugin to render the coverages.

**Comment by panaaj** [comment]
Freeboard (or any client) will use whatever the metadata presents to display a map boundary.
So from a v2 Chart spec perspective we have the opportunity to "enhance" the SK chart metadata for bounds to define a polygon rather than [left,bottom, right, top]. ]Could be included in [Charts-plugin PR 27](https://github.com/SignalK/charts-plugin/pull/27)

**Comment by AndreasSchutz** [comment]
Sound terrific to me. Right now I only have rectangular maps. Maybe the "toggle bounds" button should be on each chart??? Theoretically, if you have a lot of small charts, even the bounds would clutter...but I don't know, just a thought.

**Comment by panaaj** [comment]
Available in v2.5
