### ISSUE TITLE
Little space on a phone with route bar

### ISSUE THREAD

**Issue by petsicola** [SignalK/freeboard-sk#131]
Hi,
There is a way to hide and show the route bar. Into a phone we have very little space and it takes a lot of space into the screen.
and the same with lateral icons. there is a way to only show the hamburger menu and show all the icons if we push in it?. 
![WhatsApp Image 2024-02-13 at 10 19 06 (1)](https://github.com/SignalK/freeboard-sk/assets/61534583/f98d1f46-97d0-4a06-a30f-37e1a3fbe3a2)
![WhatsApp Image 2024-02-13 at 10 19 06](https://github.com/SignalK/freeboard-sk/assets/61534583/add9faa7-b2ed-45af-99ce-426825da87d0)

**Comment by panaaj** [comment]
For the route/course data this can be hidden using the Hide course data option from the ... menu.
![Screenshot_20240214-082848.png](https://github.com/SignalK/freeboard-sk/assets/38519157/3471d5ba-a62e-4a77-90d8-59b0e22958c3)

With regards the menu bar that will require work.
You can raise an issue at https://github.com/SignalK/freeboard-sk.

**Comment by petsicola** [comment]
at freeboard or at slack?

**Comment by panaaj** [comment]
At the link in my last comment above (GitHub).

**Comment by panaaj** [comment]
Added ability to show / hide buttons on right-side of screen.
![image](https://github.com/SignalK/freeboard-sk/assets/38519157/efce5b43-bb83-4adf-adc4-59ca5f383860)
![image](https://github.com/SignalK/freeboard-sk/assets/38519157/0ce77cb1-9d45-46da-8f70-cfd55124d957)

Main toolbar will always remain visible.

**Comment by petsicola** [comment]
The button that you create on the right side can hide the black main bar? or collapse the main bar to a hamnburger button?. or could be transparent and show the map.

**Comment by panaaj** [comment]
Updated to hide buttons on both sides.
![image](https://github.com/SignalK/freeboard-sk/assets/38519157/ba1f3dad-c6ad-48f8-a372-3c7e96d2d81b)

**Comment by panaaj** [comment]
Available in v2.6.0 release.

**Comment by petsicola** [comment]
I'm looking for 2.6.0 release but is not active... how I can try the update? or I have to wait.

**Comment by panaaj** [comment]
I can create a beta release as there are still a few things to find finalise prior to the 2.6 release.

**Comment by panaaj** [comment]
Beta release created and can be installed using `npm i @signalk/freeboard-sk@beta` from within the `.signalk` folder on the server.

**Comment by petsicola** [comment]
I've installed the beta version... is much better that the previouse release.... for me...

**Comment by petsicola** [comment]
I think that you can supress the menu.
You can put on the button.
**routes, waypoints, notes**
load gpx
load geoson
load resource

And in the button
 **more actions**
anchor watch
playback history
change user
