### ISSUE TITLE
Feature Request: Create route from waypoints

### ISSUE THREAD

**Issue by Rhumb-Runner** [SignalK/freeboard-sk#132]
Is there already or can you add a way to create a route from waypoints? I race my sailboat and our courses often have points that are re-used from race to race. It would be very beneficial to be able to quickly create a route by selecting points from the list of waypoints.

Thanks! 
Chuck Bowers

**Comment by panaaj** [comment]
This is something that is on the list.
The plan is to have some support for this functionality in the next release.

**Comment by panaaj** [comment]
Available in v2.6.0 release.
