### ISSUE TITLE
Feature Request: Auto Login / Remember me

### ISSUE THREAD

**Issue by Rhumb-Runner** [SignalK/freeboard-sk#133]
Is there a way besides disabling SK security to have freeboard automatically log you into a read/write access or at least have a remember me that will persist for a time. I use freeboard with Kip and I frequently change between pages in Kip and have to re-login each time I move back to the freeboard page. It would be handy to not have to do that each time I go back to the freeboard page.

Thanks!
Chuck Bowers

**Comment by panaaj** [comment]
Freeboard-SK does persist the login token and should only prompt for login when the token expires.

When you say flip between pages are you referring to browser tabs?

**Comment by Rhumb-Runner** [comment]
I use Freeboard as an embedded webpage to a Kip page. I guessed you would be familiar with Kip. Kip opens in a browser window / tab (I always use it in fullscreen) and you can create as many "pages" of data display as you'd like. You can change between pages by arrow buttons on the bottom of each page without leaving the Kip browser window / tab. My current setup had 6 pages of data arranged by what I need at various times. On distance races, I generally use a page that just gives me a display of the range / bearing / VMG to the waypoint as well as my SOG / COG and basic Wind info and only flipping to the Freebaord page if the waypoint doesn't advance or to get a look at the traffic on AIS. So the token could be timing out? But, Freeboard seems to be a fresh call from the server each time as I get the message about "use Shift-reload if this message dose not disappear". My display is a touchscreen and I don't have a keyboard or mouse attached. If I need to use the keyboard I have to VNC into the RPi to access a keyboard from the VNC app which is why it would be great to not have to do that each time just to login to press the arrow button to advance the waypoint. I'm trying to figure out a way or find a app to bring up a on screen keyboard whenever you click into a text input but, haven't had any luck yet. 

I've also put a request into the Kip side of the house to see if they could have a way to Auto Login as well for any embedded webpage that requires a login for full functionality.

Thanks again for looking at this. -- Chuck

**Comment by panaaj** [comment]
It appears that flipping between pages in KIP may destroy the embedded IFrame displaying Freeboard-SK which would explain the reload screen.

There are likely to be browser security features that are causing this behaviour.

Can you please link the associated KIP issue you raised here.

**Comment by godind** [comment]
Auto-login is a feature we can collaborate to improve the UX. @Rhumb-Runner can you think of any other integration features? Kip destroys the widget on page change so I don’t think it’s something that can be changed. Not easily at least but I’m all ears for a solution.

**Comment by tkurki** [comment]
@godind imho the first step towards a solution would be to document what happens today:
- document clearly and explicitly reproducible problematic sequences
- analyse what is happening in technical terms: iframes, cookies, tokens and endpoints

**Comment by panaaj** [comment]
Freeboard-SK will now use the token returned when logged in using the Admin UI, so no additional login is required assuming the user has the appropriate permissions.

You can still login as a different user via the `Login` menu option.

**Comment by panaaj** [comment]
I believe this is now addressed in KIP 2.9.0 / Freeboard-SK v2.6.1
