### ISSUE TITLE
heading.

### ISSUE THREAD

**Issue by petsicola** [SignalK/freeboard-sk#138]
The heading is a bit little... I can´t see if we go in the good direction or if I go to the next waypoint. I put you an image. something to select different distances 0,5 miles, 0,27 miles 1 mile

![image](https://github.com/SignalK/freeboard-sk/assets/61534583/7a24ac2f-33c4-4f4b-acc3-a6e5b3defca0)

![image](https://github.com/SignalK/freeboard-sk/assets/61534583/2b841cb2-b96f-42f2-b888-67d8c6b83968)

**Comment by panaaj** [comment]
The image you provided appears to have a black line drawn from the vessel to the destination over the top of the vessel and heading line.
This line is not rendered by Freeboard-SK, the line it renders to a destination does not obscure the vessel or heading line.
Is it the color or length of the heading line that is the issue?
Can you please clarify.

**Comment by petsicola** [comment]
First of all. sorry, I don't know if you want sugestions. freeboard for me is perfect! 
If you want sugestions I can explain what I see in other programs.

Heading on boating is an infinite line and in opencpn you can calibrate how long is the line for heading
This is good for us because if we go in a race I can see if we are going to pass close to a rock.
In freeboard that line is not larger enough and I can't anticipate my route.

![WhatsApp Image 2024-03-02 at 08 20 08](https://github.com/SignalK/freeboard-sk/assets/61534583/27bfb5ac-998c-4995-b2e7-042107109529)

![image](https://github.com/SignalK/freeboard-sk/assets/61534583/feb795a3-3256-435e-9ba1-beec52ba4c6d)

**Comment by tkurki** [comment]
I find also an ”infinite course over ground” line useful, for example during a crossing to extrapolate ”where will this course take us”. Could be dashed or <100% opacity for less distraction.

Having marks on the line per unit of time can also be useful.

![image](https://github.com/SignalK/freeboard-sk/assets/1049678/b5c2d169-3c9a-4190-85ba-780df8bd152d)

**Comment by panaaj** [comment]
@petsicola Thanks for clarifying.
I will look to add a configuration option for the heading line.

**Comment by tkurki** [comment]
Just to be clear: cog, not heading, right?

**Comment by panaaj** [comment]
Both:
1. Option to define the length of the heading line.
2. Add COG line

**Comment by panaaj** [comment]
Released in v2.6.1

**Comment by petsicola** [comment]
I have try it and I Like it. very good option.

**Comment by petsicola** [comment]
after try it. I could say yo two enhancements..
1º In our regattas a good optiom could be 1 and 2 nautic miles in settings
2º The line in opencpn and boating (navionics) is red. could be a good color red?
![Screenshot_2024-03-24-21-59-01-173_com android chrome](https://github.com/SignalK/freeboard-sk/assets/61534583/42e4d121-0d3f-4f98-868e-946ac157db5c)

**Comment by panaaj** [comment]
Red is currently used for tracks so probably not a great choice in this case

**Comment by panaaj** [comment]
Will add 1NM and 2NM options in the next release.
