### ISSUE TITLE
delete menu.

### ISSUE THREAD

**Issue by petsicola** [SignalK/freeboard-sk#139]
I think that you can supress the menu menu and the button menu.
You can put on the button.
**routes, waypoints, notes**
load gpx
load geoson
load resource

And in the button
 **more actions**
anchor watch
playback history
change user

**Comment by panaaj** [comment]
Given the increasing number of  features making their way into Freeboard-SK, the menu will have to remain to avoid clutter and also to avoid any need to have flyout / layered menus.

It is likely that this will need to be revisited in the future but for now the current menu will remain.

**Comment by petsicola** [comment]
ok, perfect!
I say that because Settings is in two menusand then I was thinking about the order of menus.... sorry for my comment
