### ISSUE TITLE
Measure,  distance and angles

### ISSUE THREAD

**Issue by petsicola** [SignalK/freeboard-sk#145]
Measure gives the distance of the measure. could be a good idea give distance and angle of measure. This is important for us because we need to know the next sail that we have to put in the next leg.

  
![image](https://github.com/SignalK/freeboard-sk/assets/61534583/5704fd6f-aae9-4eb5-9666-c5adfea2dad1)

**Comment by panaaj** [comment]
v2.7.0 displays angles when measuring.
