### ISSUE TITLE
enhancement of waypoints

### ISSUE THREAD

**Issue by petsicola** [SignalK/freeboard-sk#146]
There is an option to create a waypoint where the vessel is now with a generic name?

1º i push the button
![image](https://github.com/SignalK/freeboard-sk/assets/61534583/eccb2b01-ffae-4eef-acd6-f531849ca3e8)

2º Create the waypoint with a default name "waypoint 1". after that I will modify the name if I want.

3º The modification window would be the generic.
![image](https://github.com/SignalK/freeboard-sk/assets/61534583/b2422dd6-1537-4622-a783-05d4cfd81e2a)

Boating works as I say you here.

**Comment by panaaj** [comment]
v2.7.0 now adds a default waypoint name so you just need to click `Save`.

**Comment by petsicola** [comment]
I'm trying v2.7.0 and I need to put a resource name.. I'm making something bad?

**Comment by panaaj** [comment]
It does when selecting `Add Waypoint here` from the menu when right clicking the map.
I missed the "Add waypoint at vessel".
I will issue a patch.

**Comment by panaaj** [comment]
Fixed  in v 2.7.1
