### ISSUE TITLE
Meteo context pop-up title not updated

### ISSUE THREAD

**Issue by KEGustafsson** [SignalK/freeboard-sk#147]
If already one meteo contect pop-up is selected and another is selected right after, then title is not updated, showing initial pop-up title.
First two images show the issue, and third one is showing correct title, but pop-up need to be close in between selecting the new one.

![image](https://github.com/SignalK/freeboard-sk/assets/3332251/0d445283-ea15-46c9-97ab-7725669d20f9)

**Comment by panaaj** [comment]
v2.7.0 has the fix.
