### ISSUE TITLE
Make welcome screen skippable via URL params

### ISSUE THREAD

**Issue by bergie** [SignalK/freeboard-sk#148]
Now we often get the welcome popup after an upgrade. This is somewhat awkward on a kiosk screen without a mouse.

![20240403_085608](https://github.com/SignalK/freeboard-sk/assets/3346/8e9b2245-da75-4fc9-8ff3-ab5d2147a829)

Would be nice to be able to skip it via URL parameters. 

See also #110

**Comment by panaaj** [comment]
I will add  a `kiosk` query parameter.

**Comment by panaaj** [comment]
Does kiosk mode need to suppress other features like alarms, input, etc?

**Comment by bergie** [comment]
I guess that would be helpful, yes. Could start with buttons hidden

**Comment by panaaj** [comment]
v2.7.0 now supports kiosk mode.

e.g. `http://server:port/@signalk/freeboard-sk?kiosk`
