### ISSUE TITLE
Show windbarbs

### ISSUE THREAD

**Issue by petsicola** [SignalK/freeboard-sk#150]
Show windbarbs on truewind and next waypoint. I send two images.

![image](https://github.com/SignalK/freeboard-sk/assets/61534583/9917af1e-ca94-4fcf-a7d2-e72ea7bf097a)

![image](https://github.com/SignalK/freeboard-sk/assets/61534583/4c8e84c4-ca0b-415a-8ab0-67bf396070ff)

**Comment by panaaj** [comment]
As per #135 ... without the wind information for the destination there would be nothing for Freeboard-SK to display.
A plugin would need to populate the appropriate paths with data.

**Comment by petsicola** [comment]
not at the destination... the idea is to show true wind with barbs at our own vessel.over.  Close it... i don't know if it is a good idea...
I saw it in opencpn.

![image](https://github.com/SignalK/freeboard-sk/assets/61534583/620e31d4-35a8-44e6-aad8-0b856ca09536)
