### ISSUE TITLE
measure.

### ISSUE THREAD

**Issue by petsicola** [SignalK/freeboard-sk#153]
Measure gives degrees. Is a very good option for us. but is easy to use with the mouse but not with the fingers. navionics has a tool to take with the fingers two pins to put it where you want. 
![image](https://github.com/SignalK/freeboard-sk/assets/61534583/ca79d42b-a77c-49e2-a0cc-16b5a1462dd5)

**Comment by panaaj** [comment]
v2.8.0 has some improvements in this area which hopefully address this.

**Comment by petsicola** [comment]
yes. I see. I'm very happy with this version. blue line is pretty for measure and I'm trying the measure button in a pc, tablet and a mobile.
