### ISSUE TITLE
Blank tiles when zooming (North Up only)

### ISSUE THREAD

**Issue by martincaddick** [SignalK/freeboard-sk#156]
Kinda similar to issue #137
Using online maps in Europe (France).
When I have North Up selected and zoom in or out I see blank tiles every now and then. If I have heading up then it works perfectly, every time.
Any thoughts?

**Comment by panaaj** [comment]
Generally the issues identified to date have been related to the makeup of charts and definition of max min zoom.

Can you provide specific details of how you got / get the issue to occur so it can be reproduced.

**Comment by martincaddick** [comment]
Weird. Looking at http://plotter/@signalk/freeboard-sk/ in Edge I get the issue. In Google Chrome I dont get the issue now but I did a couple of days ago. Using that the same url in an iframe in nodered and I don't see the issue.

Probably not worth chasing. Please close.
