### ISSUE TITLE
Why don't you use Mapbox Style to implement the ENC display ?

### ISSUE THREAD

**Issue by viccch** [SignalK/freeboard-sk#158]
I am interested in ENC display on Web too. Using mapbox for mapping seems to be very popular recently. And I found a website that uses a technology similar to Mapbox Style to implement an awesome display. [fishing-app.gpsnauticalcharts.com](https://fishing-app.gpsnauticalcharts.com/)

**Comment by panaaj** [comment]
Freeboard-SK does support mapbox style json files.
You just need to configure it in the charts plugin.
