### ISSUE TITLE
Disabling OpenStreetMap

### ISSUE THREAD

**Issue by tkurki** [SignalK/freeboard-sk#16]
OpenStreetMap tiles are now always being fetched, even if you have area local map available and you are zoomed in and the local map covers it. With a constrained net connections this makes zero sense, as you use up resources to fetch something that is never shown.

How about treating OSM just like all the other chart layers, with the option not to show it?

Another optimisation would be to disable it when you have a raster map available and the viewport is within its bounding box. Doesn't work if the raster chart has transparent areas, though.

**Comment by tkurki** [comment]
We could also include a geojson world basemap, no download necessary.

**Comment by rob42** [comment]
The best solution is to make the WORLD map the default base map, or at least a selectable default . I set the OSM map as default as most people are likely to install and try it online, and a blank page is not very impressive if you have no charts loaded!  Likewise if you only have small scale charts loaded finding them on a white background at arbitrary zoom is near impossible. So the WORLD layer gives reference.

The processed rasters all have transparent areas, and are stacked large scale to small scale so they overlay nicely as you zoom.

**Comment by rob42** [comment]
Added open seamap
Added a toggle to freeboard-sk left menu. Default is 'online'. If you go offline openstreetmap and openseamap dissappear, and its remebered via localstorage.
Toggle online and they pop back!.
Commited just now
