### ISSUE TITLE
Improvement ideas for meteo display

### ISSUE THREAD

**Issue by tkurki** [SignalK/freeboard-sk#160]
- drop geoid, not relevant for 99.9% of users
- date on single line, has kinda special meaning in meteo context
- convert temperature to C (one desimal place) and F (no decimals)
- convert directionTrue to degrees and human language

<img width="371" alt="image" src="https://github.com/SignalK/freeboard-sk/assets/1049678/3f8cb0b4-427f-4923-9dbf-5e5fc884bc38">

**Comment by KEGustafsson** [comment]
Could meteo pop-up include e.g. wind direction similarly as AIS targets and if temperature is available then that could be also on pop-up too.
![image](https://github.com/SignalK/freeboard-sk/assets/3332251/cfca65f5-86fc-494f-ba42-799aa8a554a8)

Reference AIS target
![image](https://github.com/SignalK/freeboard-sk/assets/3332251/f6dd05a0-9be5-488d-977f-4c3b35ed25ae)

**Comment by panaaj** [comment]
With regards the display of values and their formatting....
The properties screen shows all the properties returned (including geoid if it's there).
The values should be formatted based on the available metas.
I don't believe that by default there are any for these paths.
As a workaround, enabling the weather option in Freeboard-SK plugin will send the relevant metas.
Possibly a PR for the nmea0183-signalk plugin?

**Comment by KEGustafsson** [comment]
To avoid any complicated workarounds, should relevant meteo paths included to SK specification?

**Comment by panaaj** [comment]
See... https://github.com/SignalK/specification/pull/662

**Comment by panaaj** [comment]
> Could meteo pop-up include e.g. wind speed and direction similar as AIS target showing target vessel direction and speed. If temperature is available then that could be also on pop-up too.

Did you want the wind display to be the compass rose or just text?

**Comment by KEGustafsson** [comment]
> Did you want the wind display to be the compass rose or just text?
I think compass rose would be nicer, but text is OK too.

**Comment by panaaj** [comment]
How about this?
![image](https://github.com/SignalK/freeboard-sk/assets/38519157/404e9da9-0b66-4874-8412-4f12a7bf0080)

**Comment by panaaj** [comment]
Included in v2.8.3 release

**Comment by panaaj** [comment]
Can this issue be closed?
