### ISSUE TITLE
True wind

### ISSUE THREAD

**Issue by petsicola** [SignalK/freeboard-sk#161]
True wind doesnt say the same in kip and freeboard

![image](https://github.com/SignalK/freeboard-sk/assets/61534583/743ac728-8c20-4a12-bf75-eedfb0dc0128)

This is the configuration.
![image](https://github.com/SignalK/freeboard-sk/assets/61534583/588aacf2-51c7-41a9-bec9-a7802e530a63)

**Comment by panaaj** [comment]
Are you suggesting that KIP and Freeboard-SK configuration should be the same (synchronised)?

**Comment by petsicola** [comment]
In the pictures you can see that mxtommy kip and freeboard don't give consistent data on true wind. I don't know how to solve... I don't know if tommy kip is correct or freeboard... 
It souds good be able to have a specify "global" configuration for apps to use on them but is your conclusion ;) and souds good.

**Comment by panaaj** [comment]
Fix will be in next release.

**Comment by panaaj** [comment]
Fixed in v2.8.3

**Comment by petsicola** [comment]
I tried it in v2.8.3
OK!
