### ISSUE TITLE
Feature Request: Different colors per shiptype

### ISSUE THREAD

**Issue by Donixon** [SignalK/freeboard-sk#162]
All vessels on the map have the same color on the map. (except buddy and focused I guess)
It would be nice to quickly see that something is a cargo or something. MarineTraffic does this nicely. 
(https://help.marinetraffic.com/hc/en-us/articles/205579997-What-is-the-significance-of-the-AIS-Shiptype-number)

**Comment by panaaj** [comment]
If you had to pick a small number of types to start with, what would be the most important ones be?

**Comment by Donixon** [comment]
If we had to choose, it would be useful to see the difference between inland and sea-ships. (inland is ENI-number and sea is IMO)

**Comment by Donixon** [comment]
Oh excuse me, I think you meant something else. ^Above is also important for us. But we do a lot with CARGO and TANKERS types. The 'for fun' shiptypes are not important.

**Comment by panaaj** [comment]
Great I'll start with those.
Also with regards ENI number, I'm not sure SignalK parses those.
You can check to see if they appear in the data browser on the server admin UI.
If they do can you attach a screenshot?

**Comment by Donixon** [comment]
![ima_ais](https://github.com/SignalK/freeboard-sk/assets/59081803/ea1db45f-fd6b-45c8-8355-fa672df3344f)

I can find the IMO numbers of the ships that have them in the databrowser. So I think for us it would be enough to have  toggle for 'show IMO' and 'show others' or something. If a ship has an IMO number, it most likely is a sea-going ship.

**Comment by panaaj** [comment]
The following vessel id groups will be displayed with different colors:
Cargo (70-79), Tankers (80-89), Passenger (60-69), Special (50-59)
Example of Cargo vessels in green
![image](https://github.com/SignalK/freeboard-sk/assets/38519157/cefa0384-82a7-4a6d-89d0-e6ad669ef78f)

**Comment by panaaj** [comment]
Available in v2.8.4 release.
