### ISSUE TITLE
Feature Request: Filter per shiptype

### ISSUE THREAD

**Issue by Donixon** [SignalK/freeboard-sk#163]
Our planners use Freeboard to see where a vessel is. There are a lot of different shiptypes, and not everything is needed on the map. 
Is it possible to filter per shiptype? Like hide them.
Maybe it's cool to categorize the different shiptypes so you can hide a whole category of ships. Like 'hide all crago vessels but show the tankers'.

**Comment by panaaj** [comment]
Filter by AIS Ship type available in v2.9.0

**Comment by panaaj** [comment]
I've had to withdraw v2.9.0.
It will be included in the next release.

**Comment by panaaj** [comment]
Available in v2.9.1

**Comment by Donixon** [comment]
Updated the system and it looks great. Thanks!
