### ISSUE TITLE
Feature Request: Different 'hide moored' option

### ISSUE THREAD

**Issue by Donixon** [SignalK/freeboard-sk#164]
We use the 'hide moored' option in Freeboard, but we would like to see the moored, but not so invasive as the 'not moored' vessels. Maybe it will show the moored vessels as a simple small dot on the map? (like marine traffic does)

**Comment by panaaj** [comment]
Something like this?
![image](https://github.com/SignalK/freeboard-sk/assets/38519157/1d54b638-bf95-424b-aa4d-b4d8226d440b)

**Comment by Donixon** [comment]
Yes, that is actually what we meant!

**Comment by panaaj** [comment]
Available in v2.8.4 release.
