### ISSUE TITLE
Feature Request: Focus function revamp

### ISSUE THREAD

**Issue by Donixon** [SignalK/freeboard-sk#165]
We use the 'focus vessel' function a lot, it makes the vessel red so it can be followed. But the 'red' isn't standing out a lot, you will lose it quickly in a crowed place. Maybe a simple flag on top of the focused vessel to follow it?

And when were at it, is it possible to 'flag' multiple vessels?

**Comment by panaaj** [comment]
As a short term fix (in v2.8.3), changed "focussed vessel" icon to be larger and not be hidden behind other vessels.

**Comment by panaaj** [comment]
Can we consider this done?

**Comment by Donixon** [comment]
We actually use it in a different way. But I'm not sure if it's in line as it is now. We use it as followed in another app:
 - We track multiple vessels at the same time
 - If you click on a vessel, it shows a small 'pop-up' box that stays there until you click it again (somewhat like that on-vessel-click in Freeboard, but smaller and only with information like the name and heading to)

**Comment by panaaj** [comment]
FYI, you can configure Freeboard-SK to have multiple popovers open at once.

**Comment by Donixon** [comment]
![fb_focus_flag](https://github.com/user-attachments/assets/dc5b4c87-0ef6-44bd-b1df-1f89628c3b5b)
![fb_focus_flagged](https://github.com/user-attachments/assets/bd7af011-0ba4-41c0-a1d3-6cd3358834e3)


Maybe to clarify what we mean to help a bit with the imagination:
- In the first picture you click on a vessel and there is a 'FLAG' button
- If you click that (multiple vessels is possible) the map shows the flagged vessels with a small flag. In this image we chose to show the callsign of the vessel. 

Hope this helps a bit with the explanation!

**Comment by panaaj** [comment]
That helps, thanks.

**Comment by panaaj** [comment]
Example for falgged vessels
![image](https://github.com/user-attachments/assets/6f12c173-f781-4eff-a6d9-effe9b857e55)

**Comment by Donixon** [comment]
Nice! Is it possible to put the name or callSign, if available, in the flag? This way it is quick to track if zoomed-out on the map. 
(communication    {"callsignVhf":"PA3995"} in databrwoser)

**Comment by panaaj** [comment]
Because the flag is an image it is a fixed size and text may overflow (based on it's length).
I explored other options but they all had negative impacts on map function and usability.
If the callsign is generally a fixed or if there is a max number of digits then the image can be resized to accommodate.
Not aware if there are such limits though.... can you shed some light?

**Comment by Donixon** [comment]
As far as I know is the callsign not fixed, but it has a cap of 7 characters. It starts with a specific character of a land, like P is for The Netherlands.

**Comment by panaaj** [comment]
![image](https://github.com/user-attachments/assets/126428f7-0a29-4462-aa34-02725fbe526f)

**Comment by panaaj** [comment]
Available in v2.11.0
