### ISSUE TITLE
Internet map service popup shown in kiosk mode

### ISSUE THREAD

**Issue by bergie** [SignalK/freeboard-sk#166]
Another popup that should be disabled when running in kiosk mode:
![20240624_171414](https://github.com/SignalK/freeboard-sk/assets/3346/12468706-caaf-4ef1-9c38-bd398446a6b4)

**Comment by panaaj** [comment]
Fixed in v2.9.0

**Comment by panaaj** [comment]
I've had to withdraw v2.9.0.
It will be included in the next release.

**Comment by panaaj** [comment]
Resolved in v2.9.1
