### ISSUE TITLE
Vessel no longer detected since upgrade to 2.9.0. Also no longer detecting .mbtiles charts

### ISSUE THREAD

**Issue by zubenubi** [SignalK/freeboard-sk#167]
Since an update to v 2.9.0, My vessel position is no longer detected and the 'center on vessel' button is grayed out.
![image](https://github.com/SignalK/freeboard-sk/assets/8655783/f62279f1-5154-45aa-8d30-ffc239297d8b)

In addition, I have been using .mbtiles charts for many years. Are these no longer supported? All I can see now are Open Sea Map and Open Map terrestrial. I have confirmed that the .mbtiles charts are still in their expected location at /home/pi/.signalk/charts

**Comment by tkurki** [comment]
Charts are served by the charts plugin. Is it still enabled? Status in dashboard? Any errors in syslog on server startup?

**Comment by panaaj** [comment]
I have deprecated v2.9.0 as there is an issue where the Javascript JIT compiler is throwing an error which is likely related to the update to Angular 18 and only occurs in a production build.
![image](https://github.com/SignalK/freeboard-sk/assets/38519157/e353d947-4c96-43c5-8d69-684b618525ef)

**Comment by panaaj** [comment]
v2.9.1 resolves this issue.
