### ISSUE TITLE
Route display: Show waypoints

### ISSUE THREAD

**Issue by mairas** [SignalK/freeboard-sk#168]
At the moment, routes are displayed as multiple line segments with no indicator drawn at waypoints. If the direction difference between adjacent legs is small, it can be difficult to see whether a waypoint exists. The waypoints could be indicated by small symbols, for example:

- small circle at the beginning of the route
- small rectangle at the end of the route
- small triangles pointing towards the direction of the route at intermediate waypoints

**Comment by panaaj** [comment]
@mairas Somethinglike this....
![image](https://github.com/user-attachments/assets/def39dbb-b275-4b3e-99f9-cd8163a57e5b)

**Comment by panaaj** [comment]
Available in v2.10.0 release
