### ISSUE TITLE
Provide means for deleting waypoints on touch screen

### ISSUE THREAD

**Issue by mairas** [SignalK/freeboard-sk#169]
In route editing mode, waypoint deletion is done by control-clicking. This is simple enough on a computer, but prevents deletion on a touch screen. One approach would be to activate an edit menu using a long-press. At first, the menu could just have a "delete" option.

**Comment by panaaj** [comment]
Added the ability to use `right-click` or `long press` on touch device to delete a point in the next release.

**Comment by panaaj** [comment]
closed by v2.11.2
