### ISSUE TITLE
Wind direction compass rose

### ISSUE THREAD

**Issue by tkurki** [SignalK/freeboard-sk#173]
![IMG_0794](https://github.com/user-attachments/assets/2ee6ab24-82fc-4ddd-aaf6-661a40d4a482)

i’ve found the weather data display pretty nice over the last few days of sailing! Really easy to click the meteo symbols and have the latest wind observations.

What I found confusing is the rotating compass rose for wind direction. The map underneath is north up, I would much prefer a display where the marker rotates, not the rose. This way wind direction would match the map.

**Comment by panaaj** [comment]
Will use a "north up" compass for weather stations.
![image](https://github.com/user-attachments/assets/67afd506-a0d7-4c29-9e31-e2083230ab98)

**Comment by tkurki** [comment]
I would also turn the arrow 180 degrees so that it points into the center, as the wind blows.

**Comment by panaaj** [comment]
![image](https://github.com/user-attachments/assets/7ea1ab5a-15e1-41f1-afa0-c76216f23431)
