### ISSUE TITLE
Feature Request: Filter if shipID is filled

### ISSUE THREAD

**Issue by Donixon** [SignalK/freeboard-sk#174]
Were using the new ship type function now and its great!

It would also be nice if its possible to filter sea-vessels or inland-vessels. I did some research and the filter could be as followed:
-  Type 5 AIS message carry a shipID. If that is filled, like - mmsi: 209850000 has shpid: 9355422, we know it's a sea-vessel. 

We would like to turn on or off the inland-vessels (we mostly only do work for sea-vessels).

**Comment by panaaj** [comment]
For Freeboard-SK to use shipId it needs to appear in a Signal K path.
Can you supply a screenshot of the Signal K databrowser for an inland vessel?

**Comment by Donixon** [comment]
The sea-vessels have an IMO that is under the path: registrations
![image](https://github.com/user-attachments/assets/478ed634-82f0-418c-8040-9c09ce311149)

The inland dont have this IMO. 

It would be great to turn off these inland ships and have a filter to only show vessels with IMO.

**Comment by panaaj** [comment]
Will add filter switch to filter out all "non-IMO" vessels. Will work in conjunction with other filters.

![image](https://github.com/user-attachments/assets/85e20a52-9fad-4113-a01b-44a5c95e7543)

**Comment by panaaj** [comment]
Will be in next release.

**Comment by panaaj** [comment]
v2.10.0 released with IMO filter.
