### ISSUE TITLE
Feature request: Provide a way to configure and mute sounds

### ISSUE THREAD

**Issue by mairas** [SignalK/freeboard-sk#178]
I don't (yet) use Freeboard-SK as my primary navigation app, although I hope to do that soon. As I run it alongside other apps/devices, I would like to have an option to mute the notification sounds and alarms. And possibly provide a visual indication instead - but that might belong to another issue.

**Comment by panaaj** [comment]
Presently Freeboard-SK displays alarms and plays sounds based on the `ALARM METHOD` in the notification message.

The sound can be muted but it seems you are requesting the ability to ignore the `sound` alarm method in the notification.

**Comment by panaaj** [comment]
Have added a setting option **"Do not Play Sounds"** which overrides the `ALARM_METHOD` of the notification message.

**Comment by panaaj** [comment]
closed by v2.11.2
