### ISSUE TITLE
Consider making AIS target icons larger when zoomed close in

### ISSUE THREAD

**Issue by tkurki** [SignalK/freeboard-sk#180]
When you are zoomed close in ais targets may get lost in chart detail, see the picture. Maybe target icons should grow above a certain zoom level? Having a CoG line for all vessels would also provide more visual clues, 

![IMG_1041](https://github.com/user-attachments/assets/10bf3ba2-2d59-45fd-ace5-93100573a272)

**Comment by panaaj** [comment]
v2.10.0 has scaled up the AIS icon as an inital change.
Will add COG line and investigate AIS icon size change based on zoom level in future release.

**Comment by panaaj** [comment]
![image](https://github.com/user-attachments/assets/62457baf-d294-4bdf-84c2-d0d706182d38)

**Comment by panaaj** [comment]
Available in v2.11.0

**Comment by Donixon** [comment]
Is it possible to switch off the CoG lines? In crouded places like Port of Rotterdam, it looks very busy. And some are VERY long haha.

![image](https://github.com/user-attachments/assets/e9a75ca1-6297-4ab3-99d1-2fdde3841b15)

![image](https://github.com/user-attachments/assets/74e2c429-131b-45a9-8887-3f9f291d9d51)

**Comment by panaaj** [comment]
Settings, vessels, cog line length= none

**Comment by Donixon** [comment]
![image](https://github.com/user-attachments/assets/504f1b44-bccf-4ee2-85f4-7bbaf6978093)
![image](https://github.com/user-attachments/assets/1a6aab62-14a2-471e-b35b-9830aa824f32)

Settings defaulted to 'none', but got the lines.

**Comment by panaaj** [comment]
Fix on the way.
Will add separate setting for displaying AIS COG.

**Comment by panaaj** [comment]
Fix released v2.11.1
