### ISSUE TITLE
Feature Request: instance sharing of headless server

### ISSUE THREAD

**Issue by GraffJosh** [SignalK/freeboard-sk#181]
I'm not sure if this is already available, but it's something I crave from opencpn as well. 

It would be amazing to be able to access the same instance of freeboard from multiple UI instances. For instance, signalk raspi starts a server headless then other devices connect in their browser, sharing the same instance of routes waypoints and data. 

One reason I would like this feature is to be able to close the browser and move to something else more easily. Being able to pull out my phone and check the chart (exactly the same chart that's showing at my nav station) and then close and forget about it would be perfect.

**Comment by panaaj** [comment]
What you describe is effectively how Freeboard-SK works... App runs on client and all resources (routes, waypoints, etc) are sourced from the server.

All instances see the same data from any device.

The app is effectively stateless and uses data sourced from the server.
Preferences / settings are also stored on the server if you have logged in to the server.

**Comment by GraffJosh** [comment]
Okay fantastic then I was just ignorant in my request. I have only just started using the application on my kip install and I'll have to do more testing to see how it suits me.

Thanks for getting back to me.
