### ISSUE TITLE
AIS target show 0º heading on map

### ISSUE THREAD

**Issue by KEGustafsson** [SignalK/freeboard-sk#182]
AIS target show 0º heading on map even they have other values either `navigation.headingTrue` or `navigation.courseOverGroundTrue`

AIS target info fom SK and Freeboard
![image](https://github.com/user-attachments/assets/a8658d25-b92d-4189-b077-ea6ecab305fa)
![image](https://github.com/user-attachments/assets/3ca44c51-afb0-4aa8-a442-90f75a6628a5)

**Comment by panaaj** [comment]
Out of curiosity... what is the preferred path  for Heading / COG selected in settings?

**Comment by KEGustafsson** [comment]
Preferred True / Magnetic values need to be True and then it started to show correctly. I had this Magnetic as I have heading sensor, which give magnetic out. For AIS I copy this value to True path too, so now I can use either one. True working fine.

**Comment by KEGustafsson** [comment]
I thought that this selection is only for self, but it actially is generic selection applied to all vessels.

**Comment by panaaj** [comment]
It should.
I have implemented a change for it to apply only to self.

**Comment by panaaj** [comment]
Fixed in v2.11.0
