### ISSUE TITLE
Feature request: Could it be possible to remember follow vessel?

### ISSUE THREAD

**Issue by Mastiffen** [SignalK/freeboard-sk#185]
I always use "Follow vessel" on the tablet in the front of my boat. But I have to turn it on every time I turn on the tablet. Could it be possible to make the device remember the setting, so it automatically follows when started? Or is it possible, and I have not found it?

**Comment by panaaj** [comment]
That choice is saved, so it does persist between browser reloads / starts.
One thing to note is that manually panning the map turns off "follow the vessel".  

The only way I can reproduce what you describe is when FSK is started from a shortcut on the home screen of my Android device which has it running fullscreen. 
Swiping up to switch apps sends events to FSK which appear as a gesture to "pan the map" which then disables "follow vessel" mode prior to switching away to another app.

Running from within the browser (not from the homescreen shortcut) works as expected.

**Comment by Mastiffen** [comment]
Ah, you just described my user case, with Fully Kiosk browser. Chrome doesn't support fullscreen anymore from a shortcut in newer Android, unfortunately, so I have resorted to that browser. Then I guess there is no way to avoid this, right?

**Comment by panaaj** [comment]
Unless there is a way to suppress the gesture from appearing as a map pan action.

**Comment by Mastiffen** [comment]
Or lock the follow function in settings. I would be perfectly ok with not being able to pan. And I think (but I'm not sure) that changing the zoom is taken as a pan as well, which would explain some other times where it stops following the boat.

**Comment by panaaj** [comment]
If pinch zooming then that's likely.

**Comment by Mastiffen** [comment]
Yeah, I usually do that. My perfect view would actually be only the button for show/hide buttons. I use it on an 8" rugged tablet with KIP to show the stuff I need when I am at the forward steering position, like this:
![image](https://github.com/user-attachments/assets/fbcd63a2-435a-41c2-b3be-68230187fdb0)

**Comment by Mastiffen** [comment]
Or come to think of it, since most people probably do not use it the way I do, maybe have the option to go automatically back to following the vessel after a chosen time since the last pan/touch of the screen.

**Comment by panaaj** [comment]
Added option to "lock in" Follow Vessel mode.

![image](https://github.com/user-attachments/assets/3a0e600f-7722-44f5-ac66-880d80d132ab)

Will be available in next release.

**Comment by Mastiffen** [comment]
Wow, great! Thank you so much!

**Comment by panaaj** [comment]
closed by v2.11.2
