### ISSUE TITLE
JSON parsing errors

### ISSUE THREAD

**Issue by puzzledcherry** [SignalK/freeboard-sk#187]
I'm running into errors with having the signalK server parse my JSON file. I've attached a screenshot of the server log and the JSON file. I can't seem to find the issue as to why it's not parsing.

[signalkSightings.json](https://github.com/user-attachments/files/16874598/signalkSightings.json)
![Screenshot 2024-09-04 102341](https://github.com/user-attachments/assets/760b6de6-a28a-4a98-80aa-cfb625b612b6)

**Comment by panaaj** [comment]
It appears that the errors are generated from a data source that has been configured, so this issue is not related to Freeboard-SK.

**Comment by panaaj** [comment]
Looking at the data in the error you may want to have a look at https://github.com/SignalK/freeboard-sk/wiki/Working-with-Resources

**Comment by sbender9** [comment]
https://github.com/SignalK/signalk-server/issues/1784
