### ISSUE TITLE
Incorrect display of GPS position

### ISSUE THREAD

**Issue by Colug0** [SignalK/freeboard-sk#188]
If I use the first option to display coordinates (position display format), I get the correct value (-70.03355).
With option 2 (S-28.12345°) I get W-71.03355.
With option 3 (028°15.345'S) I get -71°4202.01300'W.
With option 4 (S 28.12345°) I get W 71.03355.
Option 5 (S 28°15'46"123) is again correctly displayed as W 70° 02' 00.8082".

If it helps, I can upload screenshots.

**Comment by panaaj** [comment]
Testing on my system I can replicate the issue with Option 3 (created a fix)
 
Option 2 I get the following which is excpected: 
![image](https://github.com/user-attachments/assets/3c597f16-e9fb-4d17-a18f-52eab6421f9e)

Option 4: I get the following which is excpected: 
![image](https://github.com/user-attachments/assets/014f14cb-083c-4a47-846f-74a39de88a5b)

For these options the only thing missing from yoour example is the degree symbol.. is that the issue?

**Comment by Colug0** [comment]
Thanks for the fast replay. The error in Option 2, 3 and 4 is that it switches from 70° to 71° and in option 3 to 4202` instead of 2`:
With option 2 (S-28.12345°) I get W-71.03355.
With option 3 (028°15.345'S) I get -71°4202.01300'W.
With option 4 (S 28.12345°) I get W 71.03355.

**Comment by panaaj** [comment]
Fixed in v2.11.2

**Comment by Colug0** [comment]
Works perfect now! Thanks for the fast response and fix!
