### ISSUE TITLE
VMG to waypoint

### ISSUE THREAD

**Issue by petsicola** [SignalK/freeboard-sk#189]
VMG to waypoint. It would be interesting put a VMG to destination and st

![image](https://github.com/user-attachments/assets/9207b6b8-76ea-4837-8f32-11bcf242584b)

**Comment by panaaj** [comment]
VMG is displayed when the value is available.
This value is provided by the course provider plugin.

It appears that the VMG calculation is done  using the true values only.

I will create a PR to fix that.

**Comment by panaaj** [comment]
https://github.com/SignalK/signalk-server/issues/1787

**Comment by panaaj** [comment]
Fixed in v2.11.3
