### ISSUE TITLE
Charts - converting issue

### ISSUE THREAD

**Issue by dirkwa** [SignalK/freeboard-sk#192]
Bula from Fiji,

the Navionics charts in this area are more than questionable. Multiple times I anchored on land and they show atoll passes where none are. It is more than dangerous to sail here with sat images. With their latest update from yesterday they removed the Bing-Sat-Charts and their default sat images don't show all the reefs and even there is one it is just dark blue for them.

So looking for alternatives I stumbled on Freeboard-SK and I like it much more than the Windows 3.11 style OpenCPN.
I tried to convert with pmtiles the Charts from Bruce Chartlocker but always get errors. 
There is a "closed" ticket saying the input is crfap, but that doesn't help me as the .mbtiles work fine in OpenCPN.

Link to the bug report:
https://github.com/protomaps/go-pmtiles/issues/128

Extracted .mbtiles ot this .zip I tried:
https://download946.mediafire.com/nsgdrbjqjkngGxPA2m8-Dzhx2DOEkJlha2SmVNI7mqa1EPoTMjqQN9xa86m1AIrC_gNY9Sf1b-neiXDrJV-PQE4OuDX6lZ86xvFVTtEYPwoPQXlACsgbuhbqrevkray6PRj_Z7ofF6z8HtuwRXE_m_SCHOW_-Z_bNTylOOqM3xIG/722rc3rabytojt1/Fiji_TCL2407_Navionics.zip

Error is:
`Failed to convert MBTiles to header JSON, strconv.ParseFloat: parsing " -16.56072370": invalid syntax`

Can anyone give me a workflow/hint how to edit this file that pmtiles is happy and I (finally) can load this into Freeboard-SK?

**Comment by panaaj** [comment]
If you have the `charts-plugin` installed on the signalk server you can use the MBTiles file and avoid the issues converting the file.

https://www.npmjs.com/package/@signalk/charts-plugin

![image](https://github.com/user-attachments/assets/cafbbb58-aa42-46f8-bb42-5b6b372aac06)

**Comment by dirkwa** [comment]
@panaaj 

Super, thank you soo much. Works like charm :). I love Freeboard-SK already.

Off-topic question:
Is Freeboard-SK already supporting a radar overlay (I have the Furuno DRS4D-NXT talking TCP/IP with Timezero-Pro atm https://www.furuno.com/en/products/radar/DRS4D-NXT) ?

**Comment by panaaj** [comment]
Radar support is underway.... see the following [link in the Signal K Discord channel](https://discord.com/channels/1170433917761892493/1271894676118442034)

**Comment by dirkwa** [comment]
Awesome, hope my Furuno will make it on the list. Issue can be set as resolved. Thank you very much for your effort 🙏🍀🤞
