### ISSUE TITLE
Feature request: 24h time format and data display for Weather forecast

### ISSUE THREAD

**Issue by Haimana** [SignalK/freeboard-sk#193]
Hello,

I dare to raise this request for having an option to see the date and the time in 24h for Weather forecast.
Right now, having only the 12h time format, it is little bit confusing, especially without AM/PM in display 

![image](https://github.com/user-attachments/assets/564d1aef-ecb4-4163-8216-5925d2bac5eb)

Thank you for your attention

Best regards,
Seb

**Comment by panaaj** [comment]
It does display 24hr format.
![image](https://github.com/user-attachments/assets/dbe3a1b2-2c25-4838-a977-59208f1008e4)

**Comment by Haimana** [comment]
Huh!?
And why not for me? 
Can't find any related settings in Freeboard.
What am I missing? 
Thanks

**Comment by Haimana** [comment]
Thank you very much for your help. 
Maybe you can find a way to add the date, too.

**Comment by panaaj** [comment]
included in v2.12.0 release

**Comment by Haimana** [comment]
![image](https://github.com/user-attachments/assets/ce15d2ef-4370-48d1-878b-f5d86ac20d46)
it seems is missing a "0" but I can live with that
any chance to have the date or day nearby?
thank you

**Comment by panaaj** [comment]
As date formats vary, maybe the day will be best.

**Comment by Haimana** [comment]
yes, should be ok
thank you

**Comment by panaaj** [comment]
Fixed in V2.12.1
