### ISSUE TITLE
Feature Request: Measure tool more granular on short distances

### ISSUE THREAD

**Issue by dirkwa** [SignalK/freeboard-sk#194]
I am using the measure tool to verify my distance to coral. 
with 0.1km it is hard to guess, would be nice for distances <0.5km to have it in meter. 
Thanks a lot!

Here a sample:
https://github.com/user-attachments/assets/cbfd2f1d-a48a-4fd0-9d7a-342292f4c47b

**Comment by panaaj** [comment]
Will include in next release.... measured distances < 1km or 1NM are displayed in meters.

**Comment by dirkwa** [comment]
That would be awesome. For US users feet would be of interest, but most of them are fine with meters. Thank you very much.

**Comment by panaaj** [comment]
Will make it so for < 0.5 NM will use the depth units configured in settings.

**Comment by panaaj** [comment]
included in v2.12.0 release
