### ISSUE TITLE
[Object] instead of call sign for AIS target

### ISSUE THREAD

**Issue by dirkwa** [SignalK/freeboard-sk#199]
FB 2.12.0
SK 2.11.0

see screenshot

![image](https://github.com/user-attachments/assets/f4c2c37a-b55c-457a-a16b-766fb743c39a)

**Comment by panaaj** [comment]
Can you provide a screenshot of the DataBrowser on the server showing the callsign data.
There is an outstanding server issue and need to check this is related.

**Comment by dirkwa** [comment]
Will do later, currently on shore. Is there a way to send you a dump of my data browser data in SK?

**Comment by panaaj** [comment]
Screenshot is the easiest

**Comment by dirkwa** [comment]
Seems to be your side.


![image](https://github.com/user-attachments/assets/a7207bb8-99c3-4273-b206-a94aef3f6c38)
![image](https://github.com/user-attachments/assets/167ea186-4263-40c1-aea9-7e5a06d2ba19)
![image](https://github.com/user-attachments/assets/42041d63-e720-4ec4-8662-7d7bee3dc00a)
![image](https://github.com/user-attachments/assets/263df0ee-fc81-4b8a-ac10-887c35b8a9bf)
![image](https://github.com/user-attachments/assets/a990144f-efc5-4ff5-90c8-694c773ea972)
![image](https://github.com/user-attachments/assets/0af20a33-1f4e-4031-86c3-529e9dd8b806)

**Comment by dirkwa** [comment]
Are you fine with this or do you want me to sent additional data like f.e. a data browser dump. 
I found the plugins -to-batch and -from-batch. 
I assume they wozuld dump the data browser data and you could import them on your side.

**Comment by panaaj** [comment]
Bug found and fixed.
Will be included in the next release.
