### ISSUE TITLE
Saving resources when more than 1 resource provider

### ISSUE THREAD

**Issue by KvotheBloodless** [SignalK/freeboard-sk#200]
I am altering plugin that fetches data from ActiveCaptain and feeds the data to clients using the resources API. 
Details [here](https://github.com/itemir/signalk-activecaptain/pull/2).

Since the data is owned externally, my plugin is read-only and will throw if a PUT or POST is received. This is acceptable according to the documentation.

When Freeboard attempts to create a note/waypoint/etc... if my plugin is the first registered resource provider, it receives the write request and returns an error. Accoring to the documentation, this is expected behaviour.

> _When a request is received to create a new resource the first provider that was registered for that resource type will be the target of the requested operation (setResource())._
 
 The solution is simply for the caller to specify which plugin should handle the request.
 > _HTTP POST 'http://hostname:3000/signalk/v2/api/resources/notes?provider=provider-plugin-id_
 
 Can we please update Freeboard to explicity specify `resources-provider`as the target for write requests for resources of type 'notes'? (and probably for all other types also).

**Comment by panaaj** [comment]
We have recently merged a PR (signal K server) that allows the default provider to be set for a resource type e.g. notes.
The choice is saved in the server settings so they are persisted between restarts.
There is an API call to do this (covered in the documentation).
This will be in the next release of signal k server.

**Comment by KvotheBloodless** [comment]
@panaaj that is the ideal solution, thanks.

Happy for this issue to be closed.
