### ISSUE TITLE
Zoom level via URL params broken

### ISSUE THREAD

**Issue by bergie** [SignalK/freeboard-sk#201]
I'm loading Freeboard to our dashbord screen with the following params: `?zoom=12&northup=1&movemap=1&kiosk=1`

Of these, at least the zoom param is broken. Due to the zoom level I can't verify if movemap works either.
![20241114_110142](https://github.com/user-attachments/assets/5c6520d5-f843-4c3d-aac0-23a2a2952396)

**Comment by panaaj** [comment]
Identified bug and creating a fix.

**Comment by panaaj** [comment]
Fixed in v2.12.2
