### ISSUE TITLE
Freeboard does not interpret ENC symbols from CEVNI code (european inland waterways)

### ISSUE THREAD

**Issue by KvotheBloodless** [SignalK/freeboard-sk#202]
After converting an S57 chart using s57-tiler, Freeboard does not appear to be able to display the symbols from [the CEVNI regs](https://unece.org/fileadmin/DAM/trans/doc/finaldocs/sc3/ECE-TRANS-SC3-115-Rev.5e_WEB.pdf) (european inland waterways).

For comparison, the same chart in OpenCPN and Freeboard:
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/31810b78-e73c-4e6d-b66f-66661db4161d">
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/631974b0-7970-4011-b616-ca6cdacbe845">

The issue may be with conversion of the S57 charts to vector tiles, and if so, I will raise the issue in that repo.

**Comment by panaaj** [comment]
Ping @wdantuma

**Comment by wdantuma** [comment]
@panaaj I have a look

**Comment by panaaj** [comment]
Fixed in v2.12.2
