### ISSUE TITLE
Some resources are read-only

### ISSUE THREAD

**Issue by KvotheBloodless** [SignalK/freeboard-sk#206]
Resource provider plugins are not required to implement PUT or DELET. This is necessary because not all resources are managed locally, but instead, fetched externally with the plugin acting as a proxy/converter.

Can a read-only property be added to a resourceset's features (ResourceSet -> values -> features -> properties -> readOnly) which would supress the edit and delete icons in the UI?
<img width="248" alt="image" src="https://github.com/user-attachments/assets/9e3e7e5a-3882-4797-b4b0-458a4ca4d5d2">

**Comment by panaaj** [comment]
Do I understand correctly... you want to be able to mark individual resources `read-only` so that the provider can implement a DELETE request handler and not risk certain resources being deleted / updated?

**Comment by KvotheBloodless** [comment]
@panaaj that is correct. For better UX, the user should not be confused by seeing the delete/edit buttons when the resource is immutable.

**Comment by KvotheBloodless** [comment]
@panaaj I just had a better look at this, and was getting confused.

My comment was specific to read-only **note** resources. Other custom resource types are already read-only using the Freeboard UI.

The ticket is still valid though, some notes are immutable and the spec would support adding a readOnly property to a note.

**Comment by panaaj** [comment]
This is already supported for notes... Add `readOnly: true` to properties.

**Comment by KvotheBloodless** [comment]
> This is already supported for notes... Add `readOnly: true` to properties.

Brilliant. Closing this issue.

**Comment by panaaj** [comment]
No it's not, as it was put in place for the ca-reports plugin a few years ago.

I can add it to the Notes OpenAPI definition.
