### ISSUE TITLE
Freature Request: Boat name colors

### ISSUE THREAD

**Issue by dirkwa** [SignalK/freeboard-sk#210]
I use Freeboard-SK more and more and I am impressed, what you developed so far. Well done!.

I mostly use it for navigating with sat charts as there are no reliable chrts for the south pacific available. As you can see in the attached picture other ais boat names are hard to read on the dark backround. Would be nice if I could set the color for them to white.

![image](https://github.com/user-attachments/assets/c5e97e38-b46c-4b32-b5fd-fbaec742b5cd)

**Comment by panaaj** [comment]
You can toggle the text color using the "color drop" button (second from the bottom) on the right of your screenshot.
The text will go yellow.

**Comment by dirkwa** [comment]
Works, thanks. Can I set this as default?

**Comment by panaaj** [comment]
The setting is persisted so it will remain until you change it back

**Comment by dirkwa** [comment]
Super, thanks a lot. Topic can be closed.
