### ISSUE TITLE
The move and delete buttons are still displayed for read-only note resources

### ISSUE THREAD

**Issue by KvotheBloodless** [SignalK/freeboard-sk#214]
The read-only property correctly suppresses the edit and delete buttons in the notes detail view, but in the summary view, the move and delete buttons are still available.

<img width="1405" alt="image" src="https://github.com/user-attachments/assets/b3f679c4-86f4-4f97-9a21-058b8e528cce">

**Comment by panaaj** [comment]
fixed in upcoming release 2.12.3
