### ISSUE TITLE
A question: Offline-Maps

### ISSUE THREAD

**Issue by BenjaminBrauner** [SignalK/freeboard-sk#26]
Is there a possibility of adding offline maps? I have tried multiple ways of offline maps using openlayers but have not found a possiblity. Maybe i am just making mistakes.

**Comment by rob42** [comment]
You can use KAP/BSB charts (eg NOAA US charts, NZ charts, etc). There are many available but not for the whole world unfortunately.
To use them use https://github.com/rob42/freeboard-installer to process the charts into a tilemap, and upload into the /mapcache directory. (The java server has an upload browser page in the UI)

**Comment by tkurki** [comment]
@BenjaminBrauner see https://github.com/SignalK/signalk-server-node#charts
