### ISSUE TITLE
Use signalk-js-client and add universal functionality there

### ISSUE THREAD

**Issue by tkurki** [SignalK/freeboard-sk#3]
Freeboard-sk has the same basic functionality as most SK client apps: bootstrap server connection from /signalk, fetch self id and connect delta. 

All this is available in signalk-js-client, where different utilities and connection related logic should migrate.

Freeboard already uses npm & bundling, so using the js client should not bee too hard.

Example: freeboard [supports only uuid self id](https://github.com/SignalK/freeboard-sk/blob/master/index.js#L118).

**Comment by rob42** [comment]
Now using signalk-js-client for connections, but still need to support multiple identifiers

**Comment by panaaj** [comment]
@tkurki Can this be closed now v1.0.0 is released?
