### ISSUE TITLE
wont build

### ISSUE THREAD

**Issue by irandrews** [SignalK/freeboard-sk#32]
npm install works ok, but npm start fails with 'cant find module signalk-client'. 
Node 8.9.3 on raspbian
Install and start logs attached
[install.log](https://github.com/SignalK/freeboard-sk/files/1584700/install.log)
[start.log](https://github.com/SignalK/freeboard-sk/files/1584701/start.log)

I know there was an issue with the sk client (https://groups.google.com/forum/#!topic/signalk/2CUa0TbaiCg) but this is using the 0.1.4 client. Even installing it manually doesn't seem to fix the issue.

**Comment by tkurki** [comment]
I believe I fixed this, please try again.
