### ISSUE TITLE
AIS vessels position wrong

### ISSUE THREAD

**Issue by joabakk** [SignalK/freeboard-sk#34]
I have made a plugin to retrieve AIS vessel data from MarineTraffic API. The positions are ok in the signal k tree and in maptracker:
![image](https://user-images.githubusercontent.com/2553029/35024821-00ac67b8-fb85-11e7-9045-09c718284713.png)
But in freeboard-sk the vessel is placed 90 degrees to the south of the latitude:
![image](https://user-images.githubusercontent.com/2553029/35024855-2ca71fe8-fb85-11e7-8ab9-5630180ffe44.png)

**Comment by tkurki** [comment]
No way to reproduce this with the data you gave. What plugin? Where? What does the data that you get from websocket look like?

**Comment by joabakk** [comment]
My plugin signalk-marinetraffic-api. One logfile and a websocket (from a replay) are located at https://gist.github.com/joabakk/fd1bedfbad70183cdeec1fdbafbff487

**Comment by tkurki** [comment]
Your latlongs are strings, they should be numbers - no quotes.

**Comment by joabakk** [comment]
Ah, my bad. I was tricked by maptracker's acceptance, and the semi-acceptance of freeboard-sk. Thank you very much for checking and my apologies
