### ISSUE TITLE
Doesnt recognise self

### ISSUE THREAD

**Issue by irandrews** [SignalK/freeboard-sk#35]
The latest code seems to be confused when trying to identify your own vessel, and will post it as an AIS target instead. This is because the code expects the selfId to just be the uuid, whereas it actually comes in as 'vessels'.uuid
There could be a number of fixes, but the quickest seems to be to change line 211 in index.js from:
```
window.ownVessel = data
```
to something like:
```
window.ownVessel = data.split(".")[1]
```

**Comment by panaaj** [comment]
[https://github.com/SignalK/freeboard-sk/pull/44](url) addresses this to correct vessel data values display.
