### ISSUE TITLE
Seriously outdated dependencies with vulnerabilities

### ISSUE THREAD

**Issue by tkurki** [SignalK/freeboard-sk#45]
The dependencies of Freeboard are seriously outdated and there are critical vulnerabilities in the dependencies.  Stuff like ancient JQuery and Openlayers.

**Comment by tkurki** [comment]
I am very reluctant to publish a new version of Freeboard, as it indicates that somebody is maintaining this software.

@rob42 @joabakk @panaaj @RBerliner would any of you be interested in bringing the dependencies up to date? I have no idea what updating to current Openlayers and JQuery would mean effortwise. One easy way to check...

**Comment by rob42** [comment]
I can have a go at it later in the week. jQuery should be easy, openlayers is going to be some effort, they change apis, and the api functionality is complex.

**Comment by panaaj** [comment]
If there is a lot of work to get it up to date should we entertain putting the effort into using a framework such as Angular? I’m happy to help out where I can.

**Comment by rob42** [comment]
Yes, thats the bigger plan. Openlayers (rather than leaflet) allows for chart rotation and 3d views, so it has merit in keeping this going. I had plans to create an angular module so it could plug into Kip etc, or maybe just a straight angular app.
I'm a java dev, and crap at js. Any help appreciated.

**Comment by panaaj** [comment]
I am currently putting the finishing touches on a port of Freeboard-SK to Angular.
I should be ready to create a PR in the next day or so (time permitting).

### Included in the Release:

#### Chart Display:

- *(online)*OpenStreetMap, OpenSeaMap, and WORLD chart outline
- Hosted on Signal K server *(requires @signalk/charts-plugin)*

#### Resources:  Routes and Waypoints

    - List / Select resources hosted on Signal K server
    - Set an active Route
    - Edit Route / Waypoint properties *(Name, Description)*
    - Draw Route
    - Add Waypoint at: Cursor or Vessel position
    - Delete Waypoint(s) / Route(s) *(requires resource provider plugin e.g. GPXLoad)*

#### Map Display:

    - North-up or Vessel-up 
    - Moving Map or Moving Vessel
    - Vessel Heading / Bearing lines
    - Wind true direction / apparent angle lines

#### Alarms:

    - Display both visual and audio alarm indication as specified by the received *Notification* message
    - Anchor Watch: set radius and raise / drop anchor *(requires signalk-anchor-watch plugin)*
    - Depth *Notification* display.

#### Integration: 

Freeboard allows you to select installed *Applications* to use for the following:

- **Instrument panel**: *(default: `@SignalK/InstrumentPanel`)*

Selected application will be displayed in the Instrument panel drawer.

- **Resource Manager**: *(default: `none`)*

When selected provides a link to the application at the top of the menu drawer.

**Comment by panaaj** [comment]
[Pull Request #46](https://github.com/SignalK/freeboard-sk/pull/46) created.

**Comment by panaaj** [comment]
v1.0.0 released. Addresses this specific issue.
