### ISSUE TITLE
feature request: legend or label for each vessel

### ISSUE THREAD

**Issue by joabakk** [SignalK/freeboard-sk#50]
It would be great to have the option to show the name of each vessel on the map, so that for a number of vessels, the user does not need to click each one to identify them

**Comment by panaaj** [comment]
AIS target labels implemented in [Commit #18853976343593548f33d7eb7b1863fd5b24dcd8](https://github.com/SignalK/freeboard-sk/pull/51/commits/18853976343593548f33d7eb7b1863fd5b24dcd8)

**Comment by panaaj** [comment]
Updated to display the following attributes (when they are available) in this order:
1. target name 
2. call sign
3. MMSI

**Comment by panaaj** [comment]
Fixed and available in 1.0.0-0 pre-release
