### ISSUE TITLE
AIS Target rendering performance.

### ISSUE THREAD

**Issue by panaaj** [SignalK/freeboard-sk#53]
![image](https://user-images.githubusercontent.com/1049678/46102630-76334100-c1d7-11e8-8318-22b517adbd9a.png)
and after a while
![image](https://user-images.githubusercontent.com/1049678/46102762-c6120800-c1d7-11e8-8f2f-c3b59b1a3118.png)
as you can see from the timestamps and blocked times it is spending most of the time executing js.

And it gets worse.

_Originally posted by @tkurki in https://github.com/SignalK/freeboard-sk/pull/51#issuecomment-424835637_

**Comment by panaaj** [comment]
Commit [#f373a8b](https://github.com/SignalK/freeboard-sk/pull/51/commits/f373a8bd9aeee87b86d6a7aea732ba042a3bda65) addresses this issue.

**Comment by tkurki** [comment]
I have absolutely no idea how Angular works, but based on the cursory peek into the code it looks to me that you are looping over all the accumulated data for each incoming delta, instead of just updating the part that is actually updated. This not just for ais targets, but all data.

Do you have logic to remove stale ais targets? Deltas just stop for them when they go out of range.

**Comment by panaaj** [comment]
It is best practise in Angular to use `immutable` objects where possible to support accurate and efficient change detection, especially where arrays and objects are involved.

So in the example of AIS targets... the underlying Map object is updated in a targeted way but if used as the component data source change detection will not necessarily see the individual attribute changes and trigger an update.... hence building the current values into an `immutable` array and providing it as the data source.

That being said I am continuing to tune the 'message processing' now that the major performance obstacle seems to be resolved. Once we are happy it is resolved I will add the removal of `stale AIS targets`. 
Just so we are all on the same page: `Stale= no update in a prescribed period`, so open suggestions as to what is considered a reasonable `prescribed period` as I know there are likely to be different opinions here.

**Comment by panaaj** [comment]
Commit [#de7ff8a](https://github.com/SignalK/freeboard-sk/pull/51/commits/de7ff8af59edb1ebf041f633aa76e3060366cf85) streamlines `onMessage` handling and also AIS target rendering.
Stale AIS targets (no update in the last hr) are removed.

**Comment by panaaj** [comment]
Commit [#17f26a6](https://github.com/SignalK/freeboard-sk/pull/51/commits/17f26a6cef568ddd8c98516a5209a4bfde6055da) should now close this.

Active = last update received < 3 mins
Inactive= last update received > 6 mins
Removed when last update received > 9 mins

**Comment by joabakk** [comment]
This is sound practice for most use cases, but for a kiosk showing hourly updates worldwide from Marinetraffic or similar, I would like to have this user configurable.

**Comment by panaaj** [comment]
Fixed and available in 1.0.0-0 pre-release.
