### ISSUE TITLE
Unexpected subscribe message

### ISSUE THREAD

**Issue by rob42** [SignalK/freeboard-sk#57]
Using v1.0.0, connecting to artemis server. The default subscribe message is:
```
{
	"subscribe": [{
		"path": "none",
		"playbackRate": -1.0,
		"period": 1000,
		"minPeriod": 1000,
		"format": "delta",
		"startTime": "1970-01-01T00:00:00.000Z",
		"policy": "ideal"
	}],
	"context": "vessels.self"
}
```
path=none caused a failure as its not a vaid signalk path. Is 'none' a valid request? I would normally use '*' or just "", which has an implicit * (in artemis at least)

playbackRate is not required for normal api, but doesnt hurt. -1.0 as value is reasonable, Ive done the same, but better if its not there.

startTime is also not needed. The default unix epoch start (1970) caused an attempt to playback from then :-)  No value or blank would be better

**Comment by rob42** [comment]
BTW getting all /vessels/self/ data could result in a lot of data. Would be better to ask for the data thats actually required.

**Comment by panaaj** [comment]
It connects to delta stream using:  `ws://host:port/signalk/v1/stream?subscribe=none`

Spec for streaming api says.....
 _You can specify the contents of the strea by using the `subscribe` query parameter.

- ws://hostname/signalk/«version»/stream?subscribe=self
- ws://hostname/signalk/«version»/stream?subscribe=all
- ws://hostname/signalk/«version»/stream?subscribe=none_

So this is a valid connection query string according to the spec.

Upon successful connection it sends the following subscription requests:
```     let selfPolicy='fixed';
        let aisSub = {
            "context":"vessels.*",
            "subscribe":[
                {"path":"uuid","period":10000,"policy":selfPolicy},
                {"path":"name","period":10000,"policy":selfPolicy},
                {"path":"communication.callsignVhf","period":10000,"policy":selfPolicy},
                {"path":"mmsi","period":10000,"policy":selfPolicy},
                {"path":"port","period":10000,"policy":selfPolicy},
                {"path":"flag","period":10000,"policy":selfPolicy},
                {"path":"navigation.position","period":10000,"policy":selfPolicy},
                {"path":"navigation.state","period":10000,"policy":selfPolicy},
                {"path":"navigation.courseOverGround*","period":10000,"policy":selfPolicy},
                {"path":"navigation.speedOverGround","period":10000,"policy":selfPolicy}
            ]
        };
        let selfSub = {
            "context":"vessels.self",
            "subscribe":[
                {"path":"navigation.*","period":1000,"policy":selfPolicy},
                {"path":"environment.wind.*","period":1000,"policy":selfPolicy},
                {"path":"notifications.*","period":1000}
            ]
        };  ```

So not sure where `playbackRate` would come into it.... that would be a history API query...

**Comment by rob42** [comment]
Looks like my code added default playback and startTime - oops. So ignore that. 
Ok, I was handling 'all', Ive added 'none' now, and will look at 'self' too. Long time since I looked at that code :-)

Seems there is another ws bug in my code that was affecting the above too so closing this.
