### ISSUE TITLE
Adding waypoint in prerelease 1.0.0

### ISSUE THREAD

**Issue by zubenubi** [SignalK/freeboard-sk#58]
Hi,

In trying to add a waypoint at the vessel position or to drop a waypoint using the cursor, I am seeing an error
![image](https://user-images.githubusercontent.com/8655783/47043866-bd6c7c00-d15c-11e8-919c-b8e178933f07.png)

Is this a problem with my server config? I am running sk node server v1.7.0 and added the latest prerelease (v1.0.0) using 'npm install...'

**Comment by panaaj** [comment]
@zubenubi Node server on it's own does not provide endpoints to accept `resources/routes` or `resources/waypoints`. If you install the `GPXLoad` plugin and enable it then your server will have support for these paths and routes and waypoints can be saved.

**Comment by zubenubi** [comment]
Thanks for this explanation. I installed GPXLoad and now I am able to drop a waypoint.
