### ISSUE TITLE
Looking for non existing chart scales

### ISSUE THREAD

**Issue by joabakk** [SignalK/freeboard-sk#61]
Great work in the transition. I have discovered that my old converted maps (TMS with tilemapresource.xml) still work, but they override the default maps even when there is no scale defined for my TMS maps. I have a set with zoom levels 5-10, but freeboard still wants to load these on top of OSM in zoom level 14. The tilemapresource.xml looks like this 
```<?xml version="1.0" encoding="utf-8"?>
	<TileMap version="1.0.0" tilemapservice="http://tms.osgeo.org/1.0.0">
	  <Title>temp.vrt</Title>
	  <Abstract></Abstract>
	  <SRS>EPSG:900913</SRS>
	  <BoundingBox minx="57.32652119567997" miny="3.51562499999999" maxx="62.91523299999943" maxy="9.14062498400509"/>
	  <Origin x="57.32652119567997" y="3.51562499999999"/>
	  <TileFormat width="256" height="256" mime-type="image/png" extension="png"/>
	  <TileSets profile="mercator">
	    <TileSet href="5" units-per-pixel="4891.96980937500030" order="5"/>
	    <TileSet href="6" units-per-pixel="2445.98490468750015" order="6"/>
	    <TileSet href="7" units-per-pixel="1222.99245234375007" order="7"/>
	    <TileSet href="8" units-per-pixel="611.49622617187504" order="8"/>
	    <TileSet href="9" units-per-pixel="305.74811308593752" order="9"/>
	    <TileSet href="10" units-per-pixel="152.87405654296876" order="10"/>
	  </TileSets>
	</TileMap>
```

The resulting screen looks like this 

![capture](https://user-images.githubusercontent.com/2553029/47119819-b59bfd00-d26c-11e8-8a1a-f5a36af1818a.JPG)

**Comment by rob42** [comment]
If these were created by the https://github.com/rob42/freeboard-installer, you may have to reprocess them. I added a scale param that freeboard-sk uses to order then in the z-plane, and yours dont have this. Or maybe the node-server is not sending the scale param out?

**Comment by joabakk** [comment]
Ok thanks. What would you recommend to use for reprocessing?

**Comment by sbender9** [comment]
I think @rob42 was just saying to reprocess with the latests freeboard-installer

**Comment by joabakk** [comment]
OK thanks again. Must be really old maps...
