### ISSUE TITLE
[feature] Add +/- buttons for zooming.

### ISSUE THREAD

**Issue by free-x** [SignalK/freeboard-sk#62]
Hi,

i'm trying to use freeboard. How I can to zoom in this WebAPP? I can't find "+"/"-" buttons. And I haven't any responce to "+"/"-" on keyboard. Only scrollmouse works fine.... 

Regards
free-x

**Comment by panaaj** [comment]
@free-x You are correct that, at present, the map will zoom only with mouse scroll or `pinch - zoom` gestures.
I will raise an issue to add `+/-` keyboard operation and screen buttons

**Comment by panaaj** [comment]
Closed by #64 ([91a4fde](https://github.com/SignalK/freeboard-sk/pull/64/commits/91a4fde54aeca71a2396a2f315e945a5f543e479))
