### ISSUE TITLE
Possible miscalculation of AWA vector line ?

### ISSUE THREAD

**Issue by zubenubi** [SignalK/freeboard-sk#65]
![image](https://user-images.githubusercontent.com/8655783/48306098-cbb37b00-e503-11e8-82d2-9203eb1aab67.png)

Attached image shows charplotter in heads up mode with the TWD matching the AWA reading on the instrumentpanel gauge. I was expecting that the green vector (AWA) should match the TWD vector since the 'vessel' is stationary.

**Comment by panaaj** [comment]
Investigation has found that vessel lines are not updated when SOG=0.
Will implement a fix as part of #64 v1.1.0 release.

**Comment by panaaj** [comment]
Closed by [bf202c5](https://github.com/SignalK/freeboard-sk/pull/64/commits/bf202c52f3e971203addcb7d43045bfcf38e6826)
