### ISSUE TITLE
Server could not activate route

### ISSUE THREAD

**Issue by barney2074** [SignalK/freeboard-sk#66]
Hello

I am having a problem with freeboard-sk
When I try to activate a route, an error message 'Server could not Activate Route' occurs
I have tried both loading a GPX file, plus creating a route in freeboard-sk

I would be thankful if anyone can assist me. thanks

Andrew

**Comment by panaaj** [comment]
Freeboard provides the `Activate Route` option which sends the route reference  to the server.
The server must accept the PUT request or else you receive the `cannot activate route` error.

Currently I’m not aware of any server or plugin that supports this request so the feature is kind of optimistic at present.

It highlights the need for a type of `Actions API` so client applications can request server actions that involve the settings of a number of API path values and /or the triggering of derived values such as DTG, XTE, etc. e,g, Activate Route, Navigate to Point, navigate to Waypoint, drop anchor, etc.

There has been some initial dialogue but nothing tangible as yet.
For now it highlights the opportunity for a plugin to provide the functionality.

**Comment by rob42** [comment]
Artemis server supports the PUT method now. It also has a reworked internal architecture to support derived values, currently true wind, declination, and some anchor watch data. Adding the derived data for route following makes sense, I will add it to the list.

I dont think this needs a signalk Actions API, its an implentation feature. In my case a RouteHandler would monitor the activeRoute key and update relevant values when a route is being followed

**Comment by rob42** [comment]
Think of it this way. The signalk server maintains and communicates the state of the vessel. Sensors, guis, and bots update that state from raw input or from changes sent by the server. So here we are looking for a bot that subscribes to activateRoute, or whatever, and then does the complex stuff when needed.

**Comment by rob42** [comment]
That also means a standalone anchorBot would work with any signalk server, so we could have them in the app store like the webapps.

**Comment by panaaj** [comment]
I don’t disagree. 
There is, I think room for a means to abstract from a client (when multiple path values needs to be set to enact an operation) the need to know which combinations paths need values.

A possible example of this would be which path values need to set in `navigation.courseGreatCircle` when:
- navigating to a waypoint
- navigating to a point / location

Where as `setting active route` is more straight forward, only one path value, the others potentially require different sets of path values to be set.
It would be good to have a consistent way of the server and any extensions/plugins to publish `functions`they provide.

**Comment by rob42** [comment]
I'm wary of making the signalk spec (as opposed to a server implementation) too broad in scope,  As I think through this more I think its natural scope is just maintaining the state of the vessel so storing state, and providing CRUD to that. 

An actions API could lead to a never ending list of functions (like N2K pgns) that are poorly supported across implementations. Even in the case of a complex action there is generally still only one key that triggers the action, even though multiple keys may need setup. The case above of `navigation.courseGreatCircle` can be handled by a RouteBot, It will know which keys to update under what circumstances, so the user only needs to select the route, set any options maybe, and activate it. The bot should be triggered and update all the other data.

Better to have a separate ecosystem of bots that can be added to any installation to suit. Also allows for those bots to be written in any language too, we need to avoid becoming dependant on a single environment. But a registry that listed available bots on the server might be useful.

**Comment by rob42** [comment]
This isnt really helping @barney2074 much! We should move this discussion to the specification 
and leave this thread to address his specific problem.

**Comment by barney2074** [comment]
great, thanks @panaaj 
I will give it a try

**Comment by panaaj** [comment]
v1.1.0-rc1 has been published to NPM which addresses this.
