### ISSUE TITLE
Waypoints are not saved correctly

### ISSUE THREAD

**Issue by rob42** [SignalK/freeboard-sk#70]
The waypoints are currently saved with a put as follows:
```
{
	"jwtToken": "eyJhbGciOiJIUzUxMiJ9.eyJ....CgUqKz1HGUQ1FZuO7Q",
	"put": [{
		"path": "resources.waypoints",
		"value": {
			"urn:mrn:signalk:uuid:66d09101-ba07-4d35-96cc-fada83094f83": {
				"feature": {
					"geometry": {
						"coordinates": [173.24395051320428, -41.25098796004664],
						"type": "Point"
					},
					"id": "",
					"type": "Feature",
					"properties": {
						"name": "Nelson",
						"cmt": "Nelson Entrance"
					}
				},
				"position": {
					"latitude": -41.25098796004664,
					"longitude": 173.24395051320428
				}
			}
		},
		"timestamp": "2019-01-24T22:12:31.537Z"
	}]
}
```
The effect of this is to set the key `resources.waypoints` to the object in `value`.
While this works for one waypoint, if another is writtem it will overwrite the current one. The message should be:

```
{
	"jwtToken": "eyJhbGciOiJIUzUxMiJ9.eyJ....CgUqKz1HGUQ1FZuO7Q",
	"put": [{
		"path": "resources.waypoints.urn:mrn:signalk:uuid:66d09101-ba07-4d35-96cc-fada83094f83",
		"value": {
			"feature": {
				"geometry": {
					"coordinates": [173.24395051320428, -41.25098796004664],
					"type": "Point"
				},
				"id": "",
				"type": "Feature",
				"properties": {
					"name": "Nelson",
					"cmt": "Nelson Entrance"
				}
			},
			"position": {
				"latitude": -41.25098796004664,
				"longitude": 173.24395051320428
			}
		},
		"timestamp": "2019-01-24T22:12:31.537Z"
	}]
}
```
This creates a new waypoint named `urn:mrn:signalk:uuid:66d09101-ba07-4d35-96cc-fada83094f83`. As other waypoints are added/edited/deleted they wont affect this one.

**Comment by rob42** [comment]
Also when saving `resources` they are in the root of the signalk tree, not under `vessels`. Hence the PUT should be to 

`/signalk/v1/api/resources/waypoints/urn:mrn:signalk:uuid:66d0...94f83` 

and not 

`/signalk/v1/api/vessels/urn:mrn:signalk:uuid:a8fb07c..270/resources/waypoints/urn:mrn:signalk:uuid:66d...94f83`

**Comment by panaaj** [comment]
Freeboard currently uses http PUT by default for sending resources to the server.
The other option is to use web socket UPDATE messages. 
Websocket PUT is not currently used.

HTTP PUT does actually target ..../vessels/self/resources.

This is more than likely a mis-alignment between my GPXLoad plugin operation (on node-server) and Artemis. Most likely due to the way I have interpreted the spec and the assumptions made to fill in the gaps. 

Seems like an opportunity to align things.

**Comment by rob42** [comment]
Ive just merged https://github.com/SignalK/specification/pull/523 into specification which clarifies the PUT message and makes `vessels.self` as the default context. But thinking about your case above  when there is no context...
So thats broken already :-(

I'll fix it now, `vessels.self` should not be a default context as it makes absolute paths like /resources difficult. Easier to include `vessels.self` when you want that then it is for the server to decide when its needed or not.

**Comment by rob42** [comment]
https://github.com/SignalK/specification/pull/536

**Comment by panaaj** [comment]
@rob42 given [SignalK/specification#536](https://github.com/SignalK/specification/pull/536) refers to websocket PUT and freeboard uses HTTP PUT, can this issue be closed?

**Comment by rob42** [comment]
No I dont think so. 
I think the http PUT is targeting the `/vessels/self` path when it should not.
Hence the PUT should be to

/signalk/v1/api/**resources/waypoints/**urn:mrn:signalk:uuid:66d0...94f83

and not

/signalk/v1/api/**vessels/self/**resources/waypoints/urn:mrn:signalk:uuid:66d...94f83

Also see Signalk/specification#538 which superceeds Signalk/specification#536

**Comment by panaaj** [comment]
I have raised a question on Slack `plugins` channel as currently the GPXLoad plugin cannot accept a put to `/signalk/v1/api/resources/waypoints` or `/signalk/v1/api/resources/routes`. 
If there is no immediate answer it may be that a change might be requires in node server to allow this.

**Comment by tkurki** [comment]
This confusion stems from trying to do HTTP over ws, when simple REST would work:
- POST to `/signalk/v1/api/resources/waypoint/` to create a new route, the server responds with 201 created and Location of the created route
- PUT to `/signalk/v1/api/resources/waypoint/<sk uuid>` to modify an existing route or to add a new one with an id that the client already knows
- DELETE to `/signalk/v1/api/resources/waypoint/<sk uuid>` to delete a route

**Comment by rob42** [comment]
See https://stackoverflow.com/questions/630453/put-vs-post-in-rest
It should be possible to create with a PUT, which also simplifies the code so you dont need to consider if a waypoint is being updated or created, just PUT it anyway.

Also with a default `/vessels/self` the server will try to execute 

PUT /signalk/v1/api/vessels/self/resources/waypoint/<sk uuid>

unless you add code to explicitly check and correct for known root paths. See #538

**Comment by tkurki** [comment]
>It should be possible to create with a PUT
 
Sure, this is why I said _add a new one_ in my comment above. 

>Also with a default `/vessels/self` the server will try to execute
>PUT /signalk/v1/api/vessels/self/resources/waypoint/

No. `context` plays no role when you use http.

**Comment by panaaj** [comment]
Have raised [/signalk-server-node/issues/738](https://github.com/SignalK/signalk-server-node/issues/738) to address HTTP PUT to `/signalk/v1/api/vessels/self/resources/*` path issue.
