### ISSUE TITLE
instruments in sidepanel use incorrect url

### ISSUE THREAD

**Issue by rob42** [SignalK/freeboard-sk#71]
Using artemis server/firefox browser. 

If I open freeboard-sk v1.0.7, go to settings, and set Kip as my instruments, refresh, then open the sidepanel, I get an error.

The current url is `https://localhost:8443/@signalk/freeboard-sk/package/public/index.html`
The attempted sidebar page is `https://localhost:8443/Kip` but the app actually exists at `https://localhost:8443/@mxtommy/kip/`, hence the failure. Same effect with other choices.

I could hardcode a redirect on the artemis server, but it would be better to have a more portable way to define available apps. 

One way would be to allow {Name,url} pairs to be specified in freeboard-sk, or to make a call to `/signalk/v1/app/list` to get available app choices.

**Comment by panaaj** [comment]
This is the remaining feature where Freeboard behaviour is detecting the server type and using: 
Node server = `/webapps`
Artemis server `/signalk/v1/apps/list`
urls to retrieve a list of webapps.

A request is sent to the appropriate url and the response expected to be consistent across servers...

The response is expected to have the following keys:
```
{ 
   name: ..., , 
   description: ... ,
   _location: ..., 
}
```
which are used to compile the target `url` as follows:
```
if(!_location) { url= `/` + name }
else { url= _location }
```
KIP entry returned by node-server looks like this... so you can see the `"_location": "/@mxtommy/kip"` is used for the url.
```
{
	"_from": "@mxtommy/kip@0.1.8",
	"_id": "@mxtommy/kip@0.1.8",
	"_inBundle": false,
	"_integrity": "sha512-NBJjKmpw34AHJOzxJlXoFVj8I/77vm+DAheJLAX74wAlTuzeLjBf8pIh2IWpw0XejHurApTahN6y5D8avXuOBw==",
	"_location": "/@mxtommy/kip",
	"_phantomChildren": {},
	"_requested": {
		"type": "version",
		"registry": true,
		"raw": "@mxtommy/kip@0.1.8",
		"name": "@mxtommy/kip",
		"escapedName": "@mxtommy%2fkip",
		"scope": "@mxtommy",
		"rawSpec": "0.1.8",
		"saveSpec": null,
		"fetchSpec": "0.1.8"
	},  
        ....
```

Can you provide a sample of what Artemis server returns for KIP.

This is clearly a server behaviour that should be documented in the spec so consistent behavour is experienced by client applications.

**Comment by rob42** [comment]
Yes a spec addition is needed. I thought we already agreed on path `signalk/v1/apps` with `list`, `search`,`install`, `remove`. `/webapps` was just the early node custom implementation? I will make a PR for the spec.

I will alter my `signalk/v1/apps/list` to return:
```
{ 
   name: ..., , 
   description: ... ,
   _location: ..., 
}

```

**Comment by rob42** [comment]
Hmm, `_location` seems oddly named, `location` or `href` (which I have) seems better. Any idea why the _ ?
I will include both `_location` and `href` for now.

**Comment by rob42** [comment]
Artemis is now returning:
```
[{
	"_location": "../@mxtommy/kip/package/public/index.html",
	"licence": "",
	"author": "Thomas St.Pierre <thomas@samoht.ca>",
	"name": "Kip",
	"description": "",
	"href": "../@mxtommy/kip/package/public/index.html",
	"repository": "https://github.com/npm/npm.git",
	"version": "0.1.8"
},
....
]

**Comment by rob42** [comment]
Thanks, it works!!
Closing now
