### ISSUE TITLE
Stuck at loading screen (1.5.1)

### ISSUE THREAD

**Issue by kledom** [SignalK/freeboard-sk#73]
After updating to version 1.5.1 (Signalk Server Node Version 1.17), my Webapp is stuck at the loading screen. Shift + reload does not help.

**Comment by panaaj** [comment]
This is generally caused by browser cache... hence the shift reload instruction.
Which browser are you using? You can try clearing the browser cache.
If that doesn’t work can you post a copy of the browser console contents here.

**Comment by kledom** [comment]
Wiping the browser cache completely fixed the issue. Thank you. I thought shift + reload would be sufficient for fixing cache issues. Seems like this is not the case. 
(I'm using firefox 68.0.2)
