### ISSUE TITLE
enhancement: weather from grib or forecast images

### ISSUE THREAD

**Issue by joabakk** [SignalK/freeboard-sk#74]
Great work! I know it must be challenging to maintain what many think of as the replacement of the chart plotter. So take this request as merely a suggestion. 
I think it would be a valuable extension to be able to overlay dynamic grib files or weather charts. I have some local current maps that I would like to use, but they do not fit in the normal chart structure because they are associated with a date and time. I'm thinking of something similar to the scroll bar in opencpn, where you can select a time for the overlay gribs to appear.

**Comment by panaaj** [comment]
I am looking into this. I’d like to implement this in a way that aligns with the Signal K data model so the feature works regardless of the signalk server implementation.

Something like a plugin that serves the GRIB data via a resources path which can displayed as layers on the map. For example the `signalk-windjs` plugin serves wind data from NOAA GRIB files as JSON from a plugin defined path rather than `resources`. It would good to have a plugin like this serve the data from a signalk api path instead.

It maybe worth raising this for discussion on a Slack channel.

**Comment by panaaj** [comment]
After some inital design work I have added some inital support for displaying JSON formatted GRIB data that is planned to be available in the next release as an `experiment`.
To display GRIB data the Signal K server will need to serve JSON output from the  [GRIB2JSON tool](https://github.com/cambecc/grib2json) for the following paths:

-  `./resources/grib`:  return a list of GRIB resource `ids` and their `headers` in the following format
```
{
	"2019101012": {
		"contents": [{
			"parameterCategory": 0,
			"parameterCategoryName": "Temperature",
			"parameterNumber": 0,
			...
			"refTime": "2019-10-10T12:00:00.000Z"
		}, {
			"parameterCategory": 2,
			"parameterCategoryName": "Momentum",
			"parameterNumber": 2,
			"parameterNumberName": "U-component_of_wind",
                      ...
                }]
          },
         "2019101018": {
               ...
         }
}
```
-  `./resources/grib/<id>`:  return all contents for the selected GRIB resource `id` 

-  `./resources/grib/<id>:<sections>`:  return selected content sections as per the supplied `<sections>` list for the selected GRIB resource `id`. 
Note: `<sections>` is the zero based index of the sections required.

_e.g.  return 3rd section (index=2) `./resources/grib/2019101018:2`_

_e.g.  return 1st and 3rd sectios (indexes= 0 & 2) `./resources/grib/2019101018:0-2`_

**Comment by panaaj** [comment]
Sample of Freeboard screenshot:
![image](https://user-images.githubusercontent.com/38519157/68917542-add5c180-07ba-11ea-9781-667a027c6445.png)

**Comment by panaaj** [comment]
[Release](https://github.com/SignalK/freeboard-sk/releases/tag/v1.8.0-rc1) available for testing.

**Comment by panaaj** [comment]
**v1.8.0 Experiment:**
 
v1.8.0 in conjuction with the `freeboard-sk-helper` plugin provides the ability to serve and display JSON formatted GRIB data.

To try this out:
1) Install the `freeboard-sk-helper` plugin
2) In Freeboard go to the bottom of the `Settings` screen and check `Experimental Features`. This will display the `GRIB` (cloud icon) button on the right side of the screen.
3) Place JSON formatted GRIB data (created by the GRIB2JSON java application) in the `.signalk/freeboard-sk-helper/grib` folder on your Signal K server.

Clicking the GRIB data button will display the GRIB panel at the bottom of the screen where you can select a GRIB file (time) and if it contains Wind Vector and / or Temperature data to display on the map. 

_Note: a `Zoom In` prompt will appear in the GRIB panel if your current zoom level is not within the zoom range that GRIB data is displayed._

**Comment by joabakk** [comment]
Wow, this is great. Thanks a lot!
