### ISSUE TITLE
Enhancement - show more details on AIS targets

### ISSUE THREAD

**Issue by torevalley** [SignalK/freeboard-sk#75]
Close to my home there is a TV/Radio mast that apparently sends out AIS..
![image](https://user-images.githubusercontent.com/55152459/67656081-0ef43d00-f953-11e9-9f99-b516269d7f87.png)

Other software interprets this differenty and show a little bit more info:

![image](https://user-images.githubusercontent.com/55152459/67656141-3814cd80-f953-11e9-949f-19dac5edbffb.png)

Close to Malmö we have this:
![image](https://user-images.githubusercontent.com/55152459/67656167-4e228e00-f953-11e9-984a-2e811a2d7190.png)
And around Landskrona som other kind of targets that does not show up i Freeboard.
![image](https://user-images.githubusercontent.com/55152459/67656204-65fa1200-f953-11e9-8050-f64abe2331d3.png)

**Comment by panaaj** [comment]
Freeboard v1.7.0 currently only displays targets reported by the server under the `...api/vessels/` path.
If you can provide a dump of the /signalk/v1/api/vessels/ path from your server for the AIS target you have identified I can see how the server is reporting it as these types of resources are normally reported as a AtoNs.

I will look to add support for AtoNs in the near future.

**Comment by tkurki** [comment]
https://github.com/SignalK/signalk-parser-nmea0183/blob/master/test/VDM.js#L70

**Comment by panaaj** [comment]
The radio TV/radio mast in question seems to be listed under ../vessels/ yet from the screen shots the class seems to be `Base Station` is this to be expected?

**Comment by tkurki** [comment]
Expected: yes (there is not base station handling in the parser), as it should be: no.

https://github.com/SignalK/signalk-parser-nmea0183/blob/master/hooks/VDM.js#L39-L49

**Comment by panaaj** [comment]
Just so I am clear, it seems that this is an issue that will be resolved in `signalk-parser-nmea0183`.

**Comment by panaaj** [comment]
[Release ](https://github.com/SignalK/freeboard-sk/releases/tag/v1.8.0-rc1) available for testing.
