### ISSUE TITLE
Coordinate display should be capped to [-180,180] / [-90,90]

### ISSUE THREAD

**Issue by tkurki** [SignalK/freeboard-sk#77]
If you zoom way out and then in "around the globe" the position display shows "wrapped" coordinate values:

![image](https://user-images.githubusercontent.com/1049678/72930364-752b0900-3d64-11ea-86d7-77b04a9161b3.png)
![image](https://user-images.githubusercontent.com/1049678/72930410-8aa03300-3d64-11ea-8b34-129cfc778078.png)

**Comment by panaaj** [comment]
I have done some initial investigation of this issues and have found the following (note Freeboard is currently using OpenLayers 5):
- Set **wrapX=false** to stop the map and resource layers wrapping
- Put in place a measure to normalise resource coordinates (-180 >= coords <=180 )

This is all good for point resources, but doing this to a route that crosses the Dateline has the following impact:
-Before normalisation
![rte-before](https://user-images.githubusercontent.com/38519157/73130154-e0196000-4042-11ea-8928-593cc88e00d5.png)

- After normalisation
![rte-after](https://user-images.githubusercontent.com/38519157/73130160-f7f0e400-4042-11ea-85ed-79ff61f97684.png)

Also wrap will probably need to be on at higher zoom levels to provide a better user experience so the map does not just cut off.

I belive OL6 may address these issues and will investigate further.

**Comment by tkurki** [comment]
I was thinking of just adjusting the displayed values. Dateline is a can of worms..

**Comment by panaaj** [comment]
Have sorted the display. I have left the wrap on and have implemented a feature where the map centre is always with in the “normalised” value range. 
I also have a solution for the dateline rendering of features, just finalising this.
