### ISSUE TITLE
UX: Have something to tell when there is no map loaded. 

### ISSUE THREAD

**Issue by FredericGuilbault** [SignalK/freeboard-sk#78]
Friends of me where testing my chartplotter, and the falsely reported that freeboard-sk was broken 

There was no internet connection or local charts in signalk-server at the time.   
So they where only seeing a grey screen, tried to zoom and pan but "nothing moved". so they got confused into thinking it was not responding. 

Althrou this is not a bug, it seem like it's not what people where expecting from it.

Maybe it should have a under layer with a small zoom 0 worldmap or a message that stipulate that no layer are displayed.

**Comment by panaaj** [comment]
I will investigate some options.
