### ISSUE TITLE
Bearing of Waypoint not updating when vessel is moving

### ISSUE THREAD

**Issue by ugobrunet** [SignalK/freeboard-sk#79]
Hello everyone,

I am quite new to the whole SK environment, so I apologise if this is not the proper place to report this observation.

I launched signalk server locally with data from NMEA file. I then created a new route.
When the route is active, I can select different waypoints (this work fine), but the Bearing value is never right and it doesn't change when the vessel is moving.

I believe that the function **processCourse** in **src/app/modules/skstream/skstream.facade.ts** lead to this. The function return on line 214 if the coordinates of the waypoint did not change. So when the vessel position changes, **course.nextPoint.bearingTrue** in line 226 is never set.

I started to play around with sk server and freeboard just a few days ago so I might have misunderstood something.
Br

**Comment by panaaj** [comment]
@ugobrunet freeboard displays these values received from the server. For this to occur you need to have the freeboard-sk-helper and derived-data plugin installed and configured.
Can you confirm that these are installed?

**Comment by panaaj** [comment]
I pushed a fix. v1.8.3.
