### ISSUE TITLE
FeatureRequest: Download Routes

### ISSUE THREAD

**Issue by ph1l** [SignalK/freeboard-sk#8]
It would be neat to download the routes in gpx or kml format.

Also, when it comes to navigation software, I think routes are usually a list waypoints you plan to travel and "tracks" may be a more appropriate term for the historical location data?

**Comment by ph1l** [comment]
Looking great, btw!

![20170325-track](https://cloud.githubusercontent.com/assets/39502/24328812/cdad979a-11a8-11e7-8189-164313b7991b.png)

**Comment by panaaj** [comment]
#51 adds support for loading waypoints and routes from GPX files.
