### ISSUE TITLE
Freeboard doesn't catch server-side anchor status

### ISSUE THREAD

**Issue by bergie** [SignalK/freeboard-sk#80]
I'm using the [anchoralarm plugin API](https://github.com/sbender9/signalk-anchoralarm-plugin) to drop and raise anchor controlled by a [simple Bluetooth button](https://github.com/meri-imperiumi/signalk-bluetooth-anchor-button). However, Freeboard doesn't catch these changes coming from the server and doesn't update the UI until I reload it:

Anchor dropped server-side, but not reflected in the UI (notice how [signalk-autostate](https://github.com/meri-imperiumi/signalk-autostate) caught it however):
<img width="1397" alt="Screenshot 2020-03-04 at 13 03 18" src="https://user-images.githubusercontent.com/3346/75877968-0d62e600-5e19-11ea-8fb9-a1cd5f2c581a.png">

After a reload it shows up:
<img width="1388" alt="Screenshot 2020-03-04 at 13 03 36" src="https://user-images.githubusercontent.com/3346/75878031-34b9b300-5e19-11ea-898f-e03e9ce49e4d.png">

Same also when raising anchor, though potentially also an issue there with the anchoralarm plugin as stated in sbender9/signalk-anchoralarm-plugin#8

**Comment by panaaj** [comment]
Have prepared a fix which is included in v1.8.5.
