### ISSUE TITLE
Empty navigation.position is not handled properly

### ISSUE THREAD

**Issue by zyxit2** [SignalK/freeboard-sk#86]
In my setup position information is coming from AIS device (Digital Yacht AIT5000). Sometimes (once every 30 minutes or so) it would loose gps signal and output navigation.position as null/undefined. At that point freeboard-sk would throw an error in fb-map.component.html at line 532 that it can't access value [0]  of dfeat.self.position and further data updates would not be reflected in the UI even after correct position data start to flow in again. The only remedy is to refresh page which is a pain.

Would be great to add better handling of this situation and not halt the whole app.

**Comment by panaaj** [comment]
Thanks for raising this. I will investigate and release a fix.

**Comment by panaaj** [comment]
v1.3.1 released with fix for this issue.
