### ISSUE TITLE
Performance low with large mbtiles files

### ISSUE THREAD

**Issue by anhorbc** [SignalK/freeboard-sk#89]
Hi!
Thank you for the great work so far. I'm sorry to say that there seems to be some performance issue with large mbtiles files. freeboard-sk works like a charm with online tile sources, but when I uploaded a 1GB+ mbtiles file, the application response suddenly got really sluggish. Sometimes it won't update at all. I first thought it might be due to the poor performance of raspberry pi, but tuktuk plotter seems to work just fine without any performance degradation. My only conclusion is that the issue is with freeboard-sk. the mbtiles file is available on request.

**Comment by panaaj** [comment]
Freeboard uses OpenLayers for its map rendering where I believe Tuk-Tuk uses Leaflet, so this may explain some of the difference.

If you can make the file available that would help with analysis of the issue.
Thanks.

**Comment by wmbutler** [comment]
@anhorbc I'm interested in playing with the offline mbtiles feature as well. Do you have a write-up or any pointers to how you configured it?

**Comment by panaaj** [comment]
@wmbutler you will need to install and configure the signal k charts plugin to locally host charts.
The plugin can be installed from the app store on the Signal k server.
Once installed you can configure it using the Plugin Config link on the server.
Then you just need to place your MBTiles file(s) in the configured folder.

**Comment by anhorbc** [comment]
> Freeboard uses OpenLayers for its map rendering where I believe Tuk-Tuk uses Leaflet, so this may explain some of the difference.
> 
> If you can make the file available that would help with analysis of the issue.
> Thanks.

@panaaj, send me your email, and I will reply with a download link for the mbtiles.

**Comment by panaaj** [comment]
@anhorbc are you on the SignalK Slack channel? If so DM me and we can organise the details

**Comment by panaaj** [comment]
closed due to inactivity.
