### ISSUE TITLE
FeatureRequest: Use openseamap instead of openstreetmap

### ISSUE THREAD

**Issue by ph1l** [SignalK/freeboard-sk#9]
Perhaps this would be a better default layer for freeboard-sk?

http://openseamap.org/index.php?id=openseamap&L=1

**Comment by rob42** [comment]
Openseamap only works when on the internet. I do use it during dev and chart verification, but I wanted a stand-alone outline that worked without connection. It also had to be relatively small and suitable for distribution.
The purpose is only to find roughly where you are. I found that if you load only a local chart, then try to zoom in on it, its nearly impossible to find in the blank screens that display when zoomed out. 
The outline just gives you a rough starting point.

**Comment by panaaj** [comment]
v1.0.0 uses both OpenSeaMap and OpenStreetMap as well as supports charts served from the Signal K server `/resources/charts` path.
