### ISSUE TITLE
Ikommunicate and AIS vessels

### ISSUE THREAD

**Issue by boatmon0** [SignalK/freeboard-sk#91]
Love freeboard-sk, looks great.  However, AIS stuff has a couple of issues.   I get that the vessel names not showing is a Ikommunicate problem.  However, I also believe that their is a freeboard-sk issue.  While sitting at the marina, vessels initially show up fine, well sort of, since they don't show the vessel name.  After a bit, they disappear.  I believe this is because the system uses the delta dataset, and sitting in our slips we don't move enough to stay "alive".  Still I turned on AIS to see who is around me, moving or not?  If I use the ikommunicate compass application, the vessels continue to show up.  

I kind of state this as if it were simple, but it's not.  Lets say I'm traveling up the river, and a work barge is in the channel.  I am approaching slowly and the barge is not moving.  Will the barge disappear before I get to it?  If I am moving toward a marina, filled with vessels that use AIS, will I still be able to know their names as I get close?

Is there some simple way for me to modify freeboard-sk so that I continue to see vessels around me that are sitting still?  I'm afraid that sitting still is equated to not signaling(transmitting).  How often does the delta data set get updated when the object does not change?  I've not seen vessels re-appear, but they might?

Sorry i'm a PITA, I love the app and am just trying to make it work for me.  When underway it's much more difficult to realize that vessels are disappearing, when in the marina, I don't have many moving targets.  

So, my equipment is a digital yacht AIT 2500, digital yacht ikommunicate, raspberry pi running signalk, couple of garmin chartplotters, radar, depth.  I'm trying to get signalK to perform better than my garmin stuff.

**Comment by panaaj** [comment]
I think the easiest thing here is to outline how AIS or vessels other than self are handled.
Yes, you are correct it’s all based on received deltas for `vessels.*`.
Targets are displayed and updated when data is received.
As AIS messages are transmitted at a frequency of approx 3 mins, to avoid displaying every vessel permanently, the following logic is applied:
If 2 consecutive messages are missed (6 min) then the vessel is displayed in orange indicating stale data.
If 3 consecutive messages are missed (9 min) then the vessel is no longer displayed.

This approach was applied to de-clutter the display, And these values are not presently configurable.
There is some work to do around AIS display as there are a number of ways people are looking to use it.
I will look at making the values described above configurable then the removal from display can be disabled if desired.

**Comment by tkurki** [comment]
If we can align iK input with the SK spec we could leave Freeboard as it is/will be, without any iK specific tweaks. https://github.com/SignalK/signalk-server/issues/1253#issuecomment-764685795

**Comment by boatmon0** [comment]
Panjaa, so maybe I still don't understand the problem I am seeing.  Your rules seem very reasonable.  Perhaps IK stops sending the targets for some reason.  I would not need to change your 6 and 9 minute rules.  Thanks for the explanation.

**Comment by panaaj** [comment]
@boatmon0 release v1.15.0 allows these times to be set by the user.
