### ISSUE TITLE
Adjustable"hide"Times and Marker for vessel lost signal

### ISSUE THREAD

**Issue by Ianknx** [SignalK/freeboard-sk#93]
Hi

Would it be possible to provide a setting for changing the hide vessel timings and also to indicate on the map which vessels have lost signal.

In busy congested areas the configured hide vessels time is to long I usually have the settings at 2 minutes for lost signal and 3 minutes to clear the vessel.

I am operating my AIS in The Solent which as you will appreciate is one of the world busiest waterways and the configured time set which I believe is 9 minutes causes a backlog of vessels on the freeboard chart.

Regards

Ian Knox

**Comment by panaaj** [comment]
This has been a topic of discussion for a little while now... so it seems a good time to implement.
Will look to include this in the next release.

**Comment by Ianknx** [comment]
One other point is that SAR aircraft are not shown on Freeboard.
