### ISSUE TITLE
OpenSeaMap overlay not working

### ISSUE THREAD

**Issue by juswes** [SignalK/freeboard-sk#94]
Really nice and simple to use software, great work you guys!
But am I the only one who does not seem to get the OpenSeaMap overlay displayed on top of the map in Freeboard?
For example, see this screenshot of an other Signal K Web app named Vesselpositions (also by the Signal K team).
<img width="1792" alt="Screenshot 2021-03-14 at 11 42 55" src="https://user-images.githubusercontent.com/1074749/111065515-782e0f00-84ba-11eb-9a19-4074bcf2b583.png">

And here is that same map location in the Freeboard Web app (note the missing Open Sea Map items).
<img width="1792" alt="Screenshot 2021-03-14 at 11 45 48" src="https://user-images.githubusercontent.com/1074749/111065628-f7234780-84ba-11eb-9680-d6c6f29b906f.png">

I have the Open Sea Map overlay turned on and ordered as the top layer. 
Plus I should be on a correct zoom level to be able to view the Open Sea Map items right?
<img width="1792" alt="Screenshot 2021-03-14 at 11 46 07" src="https://user-images.githubusercontent.com/1074749/111065637-fb4f6500-84ba-11eb-87fc-f58dcd83d9c9.png">

Am I doing something wrong or missing something here?
Also, it seems to me that the implementation of the OpenStreetMap / OpenSeaMap charting canvas in the Signal K Vesselpositions extension somehow works much smoother when zooming in and out, etc. 
Any idea why that is?

BTW. I'm really impressed at the whole Signal K setup of tools, really great work and would love to start contributing to this effort myself.

**Comment by panaaj** [comment]
You are not doing anything wrong, I have identified the bug and have prepared a patch.

As to your observation re difference in map display compared to Signal K Vesselpositions... Signal K Vesselpositions uses Leaflet as the underlying map rendering library and Freeboard uses OpenLayers so this most likely accounts for the differences.

**Comment by juswes** [comment]
Many thanks @panaaj!

And as a side note. The scroll / zoom performance issue has also gone away somehow. Scrolling and zooming is now buttery smooth again. Might had to with this issue same issue? 

Anyway, again, thanks a lot!
